# Data Preparation

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
loan_data_backup = pd.read_csv('loan.csv')

C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
loan_data = loan_data_backup.copy()

## Initial Data Exploration

In [4]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,NaN,NaN,12000,12000,12000.0,60 months,14.08,279.72,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260665,NaN,NaN,10000,10000,10000.0,36 months,11.99,332.10,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260666,NaN,NaN,12000,12000,12000.0,60 months,21.45,327.69,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260667,NaN,NaN,16550,16550,16550.0,60 months,21.45,451.94,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Above result does not show all columns we will change that using the following line of code

pd.options.display.max_columns = None

# The following line of code will display all rows if you want

#pd.options.display.max_rows = None

In [6]:
loan_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.020000,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.110000,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.890000,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.710000,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.210000,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260663,NaN,NaN,12000,12000,12000.0,60 months,14.08,279.72,C,C3,house keeper,10+ years,MORTGAGE,58000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,054xx,VT,20.88,0.0,Jan-2004,0.0,NaN,NaN,12.0,0.0,9592,39.2,34.0,w,8687.20,8687.20,5360.960000,5360.96,3312.80,2048.16,0.0,0.0,0.0,Feb-2019,279.72,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,7921.0,45212.0,2.0,2.0,0.0,1.0,24.0,35620.0,36.0,3.0,4.0,4052.0,38.0,24500.0,2.0,2.0,1.0,5.0,4110.0,1807.0,70.9,0.0,0.0,157.0,164.0,1.0,1.0,2.0,9.0,NaN,9.0,NaN,0.0,2.0,4.0,3.0,9.0,11.0,10.0,21.0,4.0,12.0,0.0,0.0,0.0,3.0,100.0,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,Skilled Labor,< 1 year,MORTGAGE,30000.0,Not Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,971xx,OR,19.28,3.0,Mar-2003,1.0,13.0,NaN,10.0,0.0,3497,20.2,26.0,w,0.00,0.00,14499.802172,14499.80,12000.00,2499.80,0.0,0.0,0.0,Aug-2018,182.74,NaN,Sep-2017,0.0,46.0,1,Joint App,135000.0,7.36,Not Verified,0.0,550.0,346404.0,0.0,1.0,1.0,1.0,8.0,9431.0,78.0,0.0,3.0,2238.0,44.0,17300.0,5.0,1.0,7.0,4.0,34640.0,9162.0,19.6,0.0,0.0,163.0,174.0,16.0,8.0,4.0,141.0,46.0,0.0,17.0,2.0,1.0,4.0,2.0,5.0,4.0,7.0,18.0,4.0,10.0,0.0,0.0,0.0,1.0,76.9,50.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,13710.0,Apr-2003,1.0,4.0,11.0,71.6,1.0,17.0,0.0,0.0,7.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260665,NaN,NaN,10000,10000,10000.0,36 months,11.99,332.10,B,B5,Teacher,10+ years,OWN,64000.0,Source Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,603xx,IL,12.96,0.0,Feb-1995,0.0,NaN,NaN,6.0,0.0,7094,70.9,13.0,w,5993.27,5993.27,5306.940000,5306.94,4006.73,1300.21,0.0,0.0,0.0,Feb-2019,332.10,Mar-2019,Feb-2019,1.0,NaN,1,Individual,NaN,NaN,NaN,0.0,77.0,189735.0,1.0,2.0,1.0,2.0,3.0,29354.0,100.0,0.0,1.0,1864.0,93.0,10000.0,0.0,0.0,3.0,3.0,31623.0,136.0,93.2,0.0,0.0,134.0,271.0,15.0,3.0,3.0,111.0,NaN,3.0,NaN,0.0,1.0,3.0,1.0,2.0,4.0,3.0,6.0,3.0,6.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260666,NaN,NaN,12000,12000,12000.0,60 months,21.45,327.69,D,D5,NaN,NaN,RENT,60000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,996xx,AK,30.82,2.0,Jul-2003,1.0,7.0,NaN,8.0,0.0,12927,34.9,17.0,w,9924.69,9924.69,5207.290000,5207.29,2075.31,3131.98,0.0,0.0,0.0,Feb-2019,327.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,535.0,65238.0,2.0,4.0,2.0,3.0,4.0,52311.0,64.0,1.0,2.0,2406.0,55.0,37000.0,0.0,12.0,4.0,5.0,8155.0,18789.0,14.6,0.0,0.0,170.0,67.0,4.0,4.0,0.0,16.0,9.0,5.0,7.0,0.0,2.0,3.0,2.0,3.0,12.0,4.0,5.0,3.0,8.0,0.0,0.0,0.0,3.0,88.2,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260667,NaN,NaN,16550,16550,16550.0,60 months,21.45,451.94,D,D5,BABYSITTER,3 years,RENT,60000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,credit_card,Credit card refinancing,112xx,NY,18.40,0.0,Apr-2014,1.0,NaN,NaN,13.0,0.0,25760,50.8,14.0,w,13541.01,13541.01,7355.500000,7355.50,3008.99,4346.51,0.0,0.0,0.0,Feb-2019,500.00,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,25760.0,2.0,0.0,0.0,0.0,NaN,0.0,NaN,3.0,8.0,6158.0,51.0,50700.0,0.0,0.0,2.0,8.0,1982.0,9816.0,49.7,0.0,0.0,NaN,41.0,3.0,3.0,0.0,10.0,NaN,0.0,NaN,0.0,5.0,12.0,5.0,5.0,0.0,13.0,14.0,12.0,13.0,0.0,0.0,0.0,3.0,100.0,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
loan_data.head() # Shows the top 5 rows

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
loan_data.tail() # Shows the bottom 5 rows

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
2260663,NaN,NaN,12000,12000,12000.0,60 months,14.08,279.72,C,C3,house keeper,10+ years,MORTGAGE,58000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,054xx,VT,20.88,0.0,Jan-2004,0.0,NaN,NaN,12.0,0.0,9592,39.2,34.0,w,8687.20,8687.20,5360.960000,5360.96,3312.80,2048.16,0.0,0.0,0.0,Feb-2019,279.72,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,7921.0,45212.0,2.0,2.0,0.0,1.0,24.0,35620.0,36.0,3.0,4.0,4052.0,38.0,24500.0,2.0,2.0,1.0,5.0,4110.0,1807.0,70.9,0.0,0.0,157.0,164.0,1.0,1.0,2.0,9.0,NaN,9.0,NaN,0.0,2.0,4.0,3.0,9.0,11.0,10.0,21.0,4.0,12.0,0.0,0.0,0.0,3.0,100.0,66.7,0.0,0.0,73948.0,45212.0,6200.0,49448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,Skilled Labor,< 1 year,MORTGAGE,30000.0,Not Verified,Oct-2017,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,971xx,OR,19.28,3.0,Mar-2003,1.0,13.0,NaN,10.0,0.0,3497,20.2,26.0,w,0.00,0.00,14499.802172,14499.80,12000.00,2499.80,0.0,0.0,0.0,Aug-2018,182.74,NaN,Sep-2017,0.0,46.0,1,Joint App,135000.0,7.36,Not Verified,0.0,550.0,346404.0,0.0,1.0,1.0,1.0,8.0,9431.0,78.0,0.0,3.0,2238.0,44.0,17300.0,5.0,1.0,7.0,4.0,34640.0,9162.0,19.6,0.0,0.0,163.0,174.0,16.0,8.0,4.0,141.0,46.0,0.0,17.0,2.0,1.0,4.0,2.0,5.0,4.0,7.0,18.0,4.0,10.0,0.0,0.0,0.0,1.0,76.9,50.0,0.0,0.0,382275.0,12928.0,11400.0,12125.0,13710.0,Apr-2003,1.0,4.0,11.0,71.6,1.0,17.0,0.0,0.0,7.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260665,NaN,NaN,10000,10000,10000.0,36 months,11.99,332.10,B,B5,Teacher,10+ years,OWN,64000.0,Source Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,603xx,IL,12.96,0.0,Feb-1995,0.0,NaN,NaN,6.0,0.0,7094,70.9,13.0,w,5993.27,5993.27,5306.940000,5306.94,4006.73,1300.21,0.0,0.0,0.0,Feb-2019,332.10,Mar-2019,Feb-2019,1.0,NaN,1,Individual,NaN,NaN,NaN,0.0,77.0,189735.0,1.0,2.0,1.0,2.0,3.0,29354.0,100.0,0.0,1.0,1864.0,93.0,10000.0,0.0,0.0,3.0,3.0,31623.0,136.0,93.2,0.0,0.0,134.0,271.0,15.0,3.0,3.0,111.0,NaN,3.0,NaN,0.0,1.0,3.0,1.0,2.0,4.0,3.0,6.0,3.0,6.0,0.0,0.0,0.0,1.0,100.0,100.0,0.0,0.0,203417.0,36448.0,2000.0,29317.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260666,NaN,NaN,12000,12000,12000.0,60 months,21.45,327.69,D,D5,NaN,NaN,RENT,60000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,996xx,AK,30.82,2.0,Jul-2003,1.0,7.0,NaN,8.0,0.0,12927,34.9,17.0,w,9924.69,9924.69,5207.290000,5207.29,2075.31,3131.98,0.0,0.0,0.0,Feb-2019,327.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,535.0,65238.0,2.0,4.0,2.0,3.0,4.0,52311.0,64.0,1.0,2.0,2406.0,55.0,37000.0,0.0,12.0,4.0,5.0,8155.0,18789.0,14.6,0.0,0.0,170.0,67.0,4.0,4.0,0.0,16.0,9.0,5.0,7.0,0.0,2.0,3.0,2.0,3.0,12.0,4.0,5.0,3.0,8.0,0.0,0.0,0.0,3.0,88.2,0.0,0.0,0.0,118975.0,65238.0,22000.0,81975.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260667,NaN,NaN,16550,16550,16550.0,60 months,21.45,451.94,D,D5,BABYSITTER,3 years,RENT,60000.0,Not Verified,Oct-2017,Current,n,NaN,NaN,credit_card,Credit card refinancing,112xx,NY,18.40,0.0,Apr-2014,1.0,NaN,NaN,13.0,0.0,25760,50.8,14.0,w,13541.01,13541.01,7355.500000,7355.50,3008.99,4346.51,0.0,0.0,0.0,Feb-2019,500.00,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,25760.0,2.0,0.0,0.0,0.0,NaN,0.0,NaN,3.0,8.0,6158.0,51.0,50700.0,0.0,0.0,2.0,8.0,1982.0,9816.0,49.7,0.0,0.0,NaN,41.0,3.0,3.0,0.0,10.0,NaN,0.0,NaN,0.0,5.0,12.0,5.0,5.0,0.0,13.0,14.0,12.0,13.0,0.0,0.0,0.0,3.0,100.0,20.0,0.0,0.0,50700.0,25760.0,19500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Displays all column names.
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'revol_bal_joint',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag',
       'hardship_type', 'hardship_reason', 'hardship_status',
       'deferral_term', 'hardship_amount', 'hardship_start_date',
       'hardship_end_date', 'payment_plan_start_date', 'hardship_length',
       'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status',
       'settlement_date', 'settlement_amount', 'settlement_percentage',
       'settlement_term'], dtype=object)

In [10]:
# Displays column names, complete (non-missing) cases per column, and datatype per column.
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 145 entries, id to settlement_term
dtypes: float64(105), int64(4), object(36)
memory usage: 2.4+ GB

In [11]:
# Returns summart statistics for numerical featutures
loan_data.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,0.0,2.258957e+06,2.260639e+06,2.260638e+06,1.102166e+06,359156.000000,2.260639e+06,2.260639e+06,2.260668e+06,2.258866e+06,2.260639e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260523e+06,580775.000000,2260668.0,1.207100e+05,120706.000000,2.260639e+06,2.190392e+06,2.190392e+06,1.394538e+06,1.394539e+06,1.394539e+06,1.394539e+06,1.350744e+06,1.394539e+06,1.191818e+06,1.394539e+06,1.394539e+06,1.394539e+06,1.394320e+06,2.190392e+06,1.394539e+06,1.394538e+06,1.394538e+06,2.210638e+06,2.190322e+06,2.185733e+06,2.184597e+06,2.260523e+06,2.260639e+06,2.121597e+06,2.190391e+06,2.190391e+06,2.190392e+06,2.210638e+06,2.187256e+06,519701.000000,1.965233e+06,740359.000000,2.190392e+06,2.190392e+06,2.190392e+06,2.202078e+06,2.190392e+06,2.190392e+06,2.190392e+06,2.190391e+06,2.190392e+06,2.202078e+06,2.107011e+06,2.190392e+06,2.190392e+06,2.190392e+06,2.190237e+06,2.185289e+06,2.259303e+06,2.260563e+06,2.190392e+06,2.210638e+06,2.210638e+06,2.190392e+06,1.080200e+05,108021.000000,108021.000000,108021.000000,106184.000000,108021.000000,108021.000000,108021.000000,108021.000000,35942.000000,10613.0,10613.000000,10613.0,10613.000000,8426.000000,10613.000000,10613.000000,33056.000000,33056.000000,33056.000000
mean,NaN,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309291e+01,4.458076e+02,7.799243e+04,NaN,1.882420e+01,3.068792e-01,5.768354e-01,3.454092e+01,72.312842,1.161240e+01,1.975278e-01,1.665846e+04,5.033770e+01,2.416255e+01,4.446293e+03,4.445295e+03,1.182403e+04,1.180594e+04,9.300142e+03,2.386352e+03,1.462469e+00,1.360740e+02,2.259328e+01,3.364015e+03,1.814580e-02,44.164220,1.0,1.236246e+05,19.251817,4.147942e-03,2.327317e+02,1.424922e+05,9.344199e-01,2.779407e+00,6.764314e-01,1.562752e+00,2.122236e+01,3.550665e+04,6.914098e+01,1.290133e+00,2.749923e+00,5.806393e+03,5.703230e+01,3.457394e+04,1.012867e+00,1.477304e+00,2.036667e+00,4.521656e+00,1.354780e+04,1.139426e+04,5.789995e+01,8.464413e-03,1.236983e+01,1.257378e+02,1.814916e+02,1.402409e+01,8.297469e+00,1.555382e+00,2.484485e+01,39.303090,7.024194e+00,35.782223,5.002082e-01,3.676069e+00,5.629468e+00,4.774183e+00,7.726402e+00,8.413439e+00,8.246523e+00,1.400463e+01,5.577951e+00,1.162813e+01,6.373958e-04,2.813652e-03,8.293767e-02,2.076755e+00,9.411458e+01,4.243513e+01,1.281935e-01,4.677109e-02,1.782428e+05,5.102294e+04,2.319377e+04,4.373201e+04,3.361728e+04,0.633256,1.538997,11.469455,58.169101,3.010554,12.533072,0.046352,0.077568,36.937928,3.0,155.006696,3.0,13.686422,454.840802,11628.036442,193.606331,5030.606922,47.775600,13.148596
std,NaN,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832114e+00,2.671737e+02,1.126962e+05,NaN,1.418333e+01,8.672303e-01,8.859632e-01,2.190047e+01,26.464094,5.640861e+00,5.705150e-01,2.294831e+04,2.471307e+01,1.198753e+01,7.547612e+03,7.546657e+03,9.889599e+03,9.884835e+03,8.304886e+03,2.663086e+03,1.150210e+01,7.258317e+02,1.271114e+02,5.971757e+03,1.508131e-01,21.533121,0.0,7.416135e+04,7.822086,6.961656e-02,8.518462e+03,1.606926e+05,1.140700e+00,3.000784e+00,9.256354e-01,1.578672e+00,2.604919e+01,4.409746e+04,2.374839e+01,1.506827e+00,2.596911e+00,5.690561e+03,2.090475e+01,3.672850e+04,1.489456e+00,2.672991e+00,2.383117e+00,3.164229e+00,1.647408e+04,1.659953e+04,2.858347e+01,1.048098e-01,7.264648e+02,5.338218e+01,9.711845e+01,1.753308e+01,9.208557e+00,1.904981e+00,3.231925e+01,22.617689,5.965411e+00,22.307239,1.350326e+00,2.324646e+00,3.382874e+00,3.037921e+00,4.701430e+00,7.359114e+00,4.683928e+00,8.038868e+00,3.293434e+00,5.644027e+00,2.710643e-02,5.616522e-02,4.935732e-01,1.830711e+00,9.036140e+00,3.621616e+01,3.646130e-01,3.775338e-01,1.815748e+05,4.991124e+04,2.300656e+04,4.507298e+04,2.815387e+04,0.993401,1.760569,6.627271,25.548212,3.275893,8.150964,0.411496,0.407996,23.924584,0.0,129.113137,0.0,9.728138,375.830737,7615.161123,198.694368,3692.027842,7.336379,8.192319
min,NaN,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,NaN,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.500000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.0,5.693510e+03,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,NaN,1.189000e+01,0.000000e+00,0.000000e+00,1.600000e+01,55.000000,8.000000e+00,0.000000e+00,5.950000e+03,3.150000e+01,1.500000e+01,0.000000e+00,0.000000e+00,4.272580e+03,4.257730e+03,2.846180e+03,6.936100e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.086400e+02,0.000000e+00,27.000000,1.0,8.340000e+04,13.530000,0.000000e+00,0.000000e+00,2.909200e+04,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,8.695000e+03,5.500000e+01,0.000000e+00,1.000000e+00,2.284000e+03,4.300000e+01,1.470000e+04,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,3.080000e+03,1.722000e+03,3.540000e+01,0.000000e+00,0.000000e+00,9.600000e+01,1.160000e+02,4.000000e+00,3.000000e+00,0.000000e+00,6.000000e+00,21.000000,2.000000e+00,17.000000,0.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.000000e+00,5.000000e+00,8.000000e+00,3.000000e+00,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.130000e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.073100e+04,2.089200e+04,8.300000e+03,1.500000e+04,1.510675e+04,0.000000,0.000000,7.000000,39.800000,1.000000,7.000000,0.000000,0.000000,16.000000,3.0,59.370000,3.0,5.000000,174.967500,5628.730000,43.780000,2227.000000,45.000000,6.000000
50%,NaN,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,NaN,1.784000e+01,0.000000e+00,0.000000e+00,3.100000e+01,74.000000,1.100000e+01,0.000000e+00,1.132400e+04,5.030000e+01,2.200000e+01,0.000000e+00,0.000000e+00,9.060870e+03,9.043080e+03,6.823385e+03,1.485280e+03,0.000000e+00,0.000000e+00,0.000000e+00,5.884700e+02,0.000000e+00,44.000000,1.0,1.100000e+05,18.840000,0.000000e+00,0.000000e+00,7.924000e+04,1.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,1.300000e+01,2.312700e+04,7.200000e+01,1.000000e+00,2.000000e+00,4.413000e+03,5.800000e+01,2.540000e+04,1.000000e+00,0.000000e+00,1.000000e+00,4.000000e+00,7.335000e+03,5.442000e+03,6.020000e+01,0.000000e+00,0.000000e+00,1.300000e+02,1.640000e+02,8.000000e+00,6.000000e+00,1.000000e+00,1.400000e+01,37.000000,5.000000e+00,33.000000,0.000000e+00,3.000000e+00,5.000000e+00,4.000000e+00,7.000000e+00,6.000000e+00,7.000000e+00,1.200000e+01,5.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.000000e+02,3.750000e+01,0.000000e+00,0.000000e+00,1.142985e+05,3.786400e+04,1.630000e+04,3.269600e+04,2.651650e+04,0.000000,1.000000,10.000000,60.200000,2.000000,11.000000,0.000000,0.000000,36.000000,3.0,119.040000,3.0,15.000000,352.605000,10044.220000,132.890000,4172.855000,45.000000,14.000000
75%,NaN,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,NaN,2.449000e+01,0.000000e+00,1.000000e+00,5.000000e+01,92.000000,1.400000e+01,0.000000e+00,2.024600e+04,6.940000e+01,3.100000e+01,6.712632e+03,6.710320e+03,1.670797e+04,1.668257e+04,1.339750e+04,3.052220e+03,0.000000e+00,0.000000e+00,0.000000e+00,3.534965e+03,0.000000e+00,62.000000,1.0,1.479950e+05,24.620000,0.000000e+00,0.000000e+00,2.132040e+05,1.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00,2.400000e+01,4.609500e+04,8.600000e+01,2.000000e+00,4.000000e+00,7.598000e+03,7.200000e+01,4.320000e+04,1.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00,1.878300e+04,1.418700e+04,8.310000e+01,0.000000e+00,0.000000e+00,1.540000e+02,2.320000e+02,1.700000e+01,1.100000e+01,3.000000e+00,3.000000e+01,57.000000,1.100000e+01,51.000000,0.000000e+00,5.000000e+00,7.000000e+00,6.000000e+00,1.000000e+01,1.100000e+01,1.000000e+01,1.800000e+01,7.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+02,7.140000e+01,0.000000e+00,0.000000e+00,2.577550e+05,6.435000e+04,3.030000e+04,5.880425e+04,4.376900e+04,1.000000,2.000000,15.000000,78.600000,4.000000,17.000000,0.000000,0.000000,56.000000,3.0,213.260000,3.0,22.000000,622.792500,16114.940000,284.180000,6870.782500,50.000000,18.000000
max,NaN,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,NaN,9.990000e+02,5.800000e+01,3.300000e+01,2.260000e+02,129.000000,1.010000e+02,8.600000e+01,2.904836e+06,8.923000e+02,1.760000e+02,4.000000e+04,4.000000e+04,6.329688e+04,6.329688e+04,4.000000e+04,2.819250e+04,1.427250e+03,3.985955e+04,7.174719e+03,4.219205e+04,2.000000e+01,226.000000,1.0,7.874821e+06,69.490000,1.400000e+01,9.152545e+06,9.971659e+06,1.800000e+01,5.700000e+01,2.500000e+01,5.100000e+01,5.110000e+02,1.837038e+06,1.000000e+03,2.800000e+01,6.000000e+01,1.170668e+06,2.390000e+02,9.999999e+06,4.800000e+01,1.110000e+02,6.700000e+01,6.400000e+01,9.580840e+05,7.111400e+05,3.396000e+02,1.000000e+01,2.499250e+05,9.990000e+02,9.990000e+02,5.470000e+02,3.820000e+02,9.400000e+01,6.610000e+02,202.000000,2.500000e+01,202.000000,5.800000e+01,5.000000e+01,7.200000e+01,7.100000e+01,8.600000e+01,1.590000e+02,9.100000e+01,1.510000e+02,6.500000e+01,1.010000e+02,7.000000e+00,4.000000e+00,5.800000e+01,3.200000e+01,1.000000e+02,1.000000e+02,1.200000e+01,8.500000e+01,9.999999e+06,3.408095e+06,1.569000e+06,2.118996e+06,1.110019e+06,6.000000,27.000000,82.000000,434.300000,43.000000,106.000000,21.000000,23.000000,185.000000,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

# Pre-processing

>- emp_length

In [12]:
# Check all unique values in a column

loan_data['emp_length'].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

As seen above there are several values containing symbols like + and <. We will use str.replace to clean these values.
We will create a new column named emp_length_int in which we will clear and store emp_length

In [13]:


loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '') # replace + years with empty string
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0)) # replace <1 year with 0 as a string
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('nan',  str(0)) # replace n/a with 0 as a string
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')  # replace with empty string
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '') # replae with empty string

C:\Users\HP\AppData\Local\Temp/ipykernel_1636/109213271.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '') # replace + years with empty string

In [14]:
# Checks the datatype of a single element of a column.

type(loan_data['emp_length_int'][0])

str

In [15]:
# Transforms the values to numeric.
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [16]:
# Checks the datatype of a single element of a column.

type(loan_data['emp_length_int'][0])

numpy.float64

>- earliest_cr_line

In [17]:
# Check earliest_cr_line column
loan_data['earliest_cr_line']

0          Apr-2001
1          Jun-1987
2          Apr-2011
3          Feb-2006
4          Dec-2000
             ...
2260663    Jan-2004
2260664    Mar-2003
2260665    Feb-1995
2260666    Jul-2003
2260667    Apr-2014
Name: earliest_cr_line, Length: 2260668, dtype: object

In [18]:
# Extracts the date and the time from a string variable that is in a given format.

loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%Y')

In [19]:
# Checks the datatype of a single element of a column.
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [20]:
# Calculates the difference between two dates and times.

pd.to_datetime('2020-12-01') - loan_data['earliest_cr_line_date']

0          7184 days
1         12237 days
2          3532 days
3          5417 days
4          7305 days
             ...
2260663    6179 days
2260664    6485 days
2260665    9435 days
2260666    6363 days
2260667    2436 days
Name: earliest_cr_line_date, Length: 2260668, dtype: timedelta64[ns]

In [21]:
# Assume we are now in December 2017
# Calculate the difference between two dates in months, turn it to numeric datatype and round it.
# Save the result in a new variable

loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']) / np.timedelta64(1, 'M')))

In [22]:
# Shows some descriptive statisics for the values of a column.
loan_data['mths_since_earliest_cr_line'].describe()

count    2.260639e+06
mean     2.156891e+02
std      9.416722e+01
min      2.500000e+01
25%      1.510000e+02
50%      2.000000e+02
75%      2.650000e+02
max      1.017000e+03
Name: mths_since_earliest_cr_line, dtype: float64

>- term

In [23]:
loan_data['term']

0           36 months
1           60 months
2           36 months
3           36 months
4           60 months
              ...
2260663     60 months
2260664     60 months
2260665     36 months
2260666     60 months
2260667     60 months
Name: term, Length: 2260668, dtype: object

In [24]:
# Descriptive statistics
loan_data['term'].describe()

count        2260668
unique             2
top        36 months
freq         1609754
Name: term, dtype: object

In [25]:
# Replace unwanted sub-strings and capture results in a new column
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')

In [26]:
loan_data['term_int']

0           36
1           60
2           36
3           36
4           60
          ...
2260663     60
2260664     60
2260665     36
2260666     60
2260667     60
Name: term_int, Length: 2260668, dtype: object

In [27]:
# Sanity check of data type of a random elemen
type(loan_data['term_int'][3])

str

In [28]:
# Change the type of the column to numeric
loan_data['term_int'] = pd.to_numeric(loan_data['term_int'])

In [29]:
# Sanity check of data type of a random elemen
type(loan_data['term_int'][3])

numpy.int64

>- issue_d

In [30]:
# check issue_d
loan_data['issue_d']

0          Dec-2018
1          Dec-2018
2          Dec-2018
3          Dec-2018
4          Dec-2018
             ...
2260663    Oct-2017
2260664    Oct-2017
2260665    Oct-2017
2260666    Oct-2017
2260667    Oct-2017
Name: issue_d, Length: 2260668, dtype: object

In [31]:
# Assume we are now in December 2017
# Extracts the date and the time from a string variable.
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%Y')

In [32]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'M')))

In [33]:
# Get statistics of new column as a sanity check
loan_data['mths_since_issue_d'].describe()

count    2.260668e+06
mean     1.895439e+01
std      2.161178e+01
min     -1.200000e+01
25%      1.000000e+00
50%      1.700000e+01
75%      3.200000e+01
max      1.260000e+02
Name: mths_since_issue_d, dtype: float64

In [34]:
# To identity the rows returning negative values, take three columns from the dataframe. 
# Then, we display them only for the rows where a variable has negative value.
loan_data.loc[: , ['issue_d', 'issue_d_date', 'mths_since_issue_d']][loan_data['mths_since_issue_d'] < 0]

         issue_d issue_d_date  mths_since_issue_d
0       Dec-2018   2018-12-01               -12.0
1       Dec-2018   2018-12-01               -12.0
2       Dec-2018   2018-12-01               -12.0
3       Dec-2018   2018-12-01               -12.0
4       Dec-2018   2018-12-01               -12.0
...          ...          ...                 ...
495237  Jan-2018   2018-01-01                -1.0
495238  Jan-2018   2018-01-01                -1.0
495239  Jan-2018   2018-01-01                -1.0
495240  Jan-2018   2018-01-01                -1.0
495241  Jan-2018   2018-01-01                -1.0

[495242 rows x 3 columns]

One solution is to replace the negative values with the maximum value

In [35]:
loan_data['mths_since_issue_d'].max() # max value in column

126.0

In [36]:
loan_data['mths_since_issue_d'].min() # # max value in column

-12.0

In [37]:
# replace negative values with max value
loan_data['mths_since_issue_d'][loan_data['mths_since_issue_d'] < 0] = loan_data['mths_since_issue_d'].max()

C:\Users\HP\AppData\Local\Temp/ipykernel_1636/1739706980.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data['mths_since_issue_d'][loan_data['mths_since_issue_d'] < 0] = loan_data['mths_since_issue_d'].max()

In [38]:
# check to ensure min value is changes
loan_data['mths_since_issue_d'].min()

0.0

In [39]:
# check issue_d
loan_data['issue_d']

0          Dec-2018
1          Dec-2018
2          Dec-2018
3          Dec-2018
4          Dec-2018
             ...
2260663    Oct-2017
2260664    Oct-2017
2260665    Oct-2017
2260666    Oct-2017
2260667    Oct-2017
Name: issue_d, Length: 2260668, dtype: object

In [40]:
# Assume we are now in December 2017
# Extracts the date and the time from a string variable.
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%Y')

In [41]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'M')))

In [42]:
# Get statistics of new column as a sanity check
loan_data['mths_since_issue_d'].describe()

count    2.260668e+06
mean     1.895439e+01
std      2.161178e+01
min     -1.200000e+01
25%      1.000000e+00
50%      1.700000e+01
75%      3.200000e+01
max      1.260000e+02
Name: mths_since_issue_d, dtype: float64

In [43]:
# To identity the rows returning negative values, take three columns from the dataframe. 
# Then, we display them only for the rows where a variable has negative value.
loan_data.loc[: , ['issue_d', 'issue_d_date', 'mths_since_issue_d']][loan_data['mths_since_issue_d'] < 0]

         issue_d issue_d_date  mths_since_issue_d
0       Dec-2018   2018-12-01               -12.0
1       Dec-2018   2018-12-01               -12.0
2       Dec-2018   2018-12-01               -12.0
3       Dec-2018   2018-12-01               -12.0
4       Dec-2018   2018-12-01               -12.0
...          ...          ...                 ...
495237  Jan-2018   2018-01-01                -1.0
495238  Jan-2018   2018-01-01                -1.0
495239  Jan-2018   2018-01-01                -1.0
495240  Jan-2018   2018-01-01                -1.0
495241  Jan-2018   2018-01-01                -1.0

[495242 rows x 3 columns]

One solution is to replace the negative values with the maximum value

In [44]:
loan_data['mths_since_issue_d'].max() # max value in column

126.0

In [45]:
loan_data['mths_since_issue_d'].min() # # max value in column

-12.0

In [46]:
# replace negative values with max value
loan_data['mths_since_issue_d'][loan_data['mths_since_issue_d'] < 0] = loan_data['mths_since_issue_d'].max()

C:\Users\HP\AppData\Local\Temp/ipykernel_1636/1739706980.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data['mths_since_issue_d'][loan_data['mths_since_issue_d'] < 0] = loan_data['mths_since_issue_d'].max()

In [47]:
# check to ensure min value is changes
loan_data['mths_since_issue_d'].min()

0.0

Date time features that needs to be converted:
>- last_pymnt_d
>- next_pymnt_d
>- last_credit_pull_d
>- sec_app_earliest_cr_line
>- hardship_start_date
>- hardship_end_date
>- payment_plan_start_date
>- debt_settlement_flag_date
>- settlement_date

>- last_pymnt_d

In [48]:
# check issue_d
loan_data['last_pymnt_d']

0          Feb-2019
1          Feb-2019
2          Feb-2019
3          Feb-2019
4          Feb-2019
             ...
2260663    Feb-2019
2260664    Aug-2018
2260665    Feb-2019
2260666    Feb-2019
2260667    Feb-2019
Name: last_pymnt_d, Length: 2260668, dtype: object

In [49]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['last_pymnt_d_date'] = pd.to_datetime(loan_data['last_pymnt_d'], format = '%b-%Y')

In [50]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_last_pymnt_d'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['last_pymnt_d_date']) / np.timedelta64(1, 'M')))

In [51]:
# Get statistics of new column as a sanity check
loan_data['mths_since_last_pymnt_d'].describe()

count    2.258242e+06
mean     3.578890e+01
std      1.801096e+01
min      2.200000e+01
25%      2.200000e+01
50%      2.800000e+01
75%      4.500000e+01
max      1.560000e+02
Name: mths_since_last_pymnt_d, dtype: float64

>- next_pymnt_d

In [52]:
# check next_pymnt_d
loan_data['next_pymnt_d']

0          Mar-2019
1          Mar-2019
2          Mar-2019
3          Mar-2019
4          Mar-2019
             ...
2260663    Mar-2019
2260664         NaN
2260665    Mar-2019
2260666    Mar-2019
2260667    Mar-2019
Name: next_pymnt_d, Length: 2260668, dtype: object

In [53]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['next_pymnt_d_date'] = pd.to_datetime(loan_data['next_pymnt_d'], format = '%b-%Y')

In [54]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_next_pymnt_d'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['next_pymnt_d_date']) / np.timedelta64(1, 'M')))

In [55]:
# Get statistics of new column as a sanity check
loan_data['mths_since_next_pymnt_d'].describe()

count    957061.000000
mean         21.261896
std           4.969863
min          20.000000
25%          21.000000
50%          21.000000
75%          21.000000
max         155.000000
Name: mths_since_next_pymnt_d, dtype: float64

>- last_credit_pull_d

In [56]:
# check next_pymnt_d
loan_data['last_credit_pull_d']

0          Feb-2019
1          Feb-2019
2          Feb-2019
3          Feb-2019
4          Feb-2019
             ...
2260663    Feb-2019
2260664    Sep-2017
2260665    Feb-2019
2260666    Feb-2019
2260667    Feb-2019
Name: last_credit_pull_d, Length: 2260668, dtype: object

In [57]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['last_credit_pull_d_date'] = pd.to_datetime(loan_data['last_credit_pull_d'], format = '%b-%Y')

In [58]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_last_credit_pull_d'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['last_credit_pull_d_date']) / np.timedelta64(1, 'M')))

In [59]:
# Get statistics of new column as a sanity check
loan_data['mths_since_last_credit_pull_d'].describe()

count    2.260595e+06
mean     2.764806e+01
std      1.139527e+01
min      2.100000e+01
25%      2.200000e+01
50%      2.200000e+01
75%      2.800000e+01
max      1.630000e+02
Name: mths_since_last_credit_pull_d, dtype: float64

>- sec_app_earliest_cr_line

In [60]:
# check next_pymnt_d
loan_data['sec_app_earliest_cr_line']

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
             ...
2260663         NaN
2260664    Apr-2003
2260665         NaN
2260666         NaN
2260667         NaN
Name: sec_app_earliest_cr_line, Length: 2260668, dtype: object

In [61]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['sec_app_earliest_cr_line_date'] = pd.to_datetime(loan_data['sec_app_earliest_cr_line'], format = '%b-%Y')

In [62]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_sec_app_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['sec_app_earliest_cr_line_date']) / np.timedelta64(1, 'M')))

In [63]:
# Get statistics of new column as a sanity check
loan_data['mths_since_sec_app_earliest_cr_line'].describe()

count    108021.000000
mean        217.054082
std          91.696472
min          30.000000
25%         162.000000
50%         200.000000
75%         261.000000
max        1041.000000
Name: mths_since_sec_app_earliest_cr_line, dtype: float64

>- hardship_start_date

In [64]:
# check next_pymnt_d
loan_data['hardship_start_date']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260663    NaN
2260664    NaN
2260665    NaN
2260666    NaN
2260667    NaN
Name: hardship_start_date, Length: 2260668, dtype: object

In [65]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['hardship_start_date_dt'] = pd.to_datetime(loan_data['hardship_start_date'], format = '%b-%Y')

In [66]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_hardship_start_date_dt'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['hardship_start_date_dt']) / np.timedelta64(1, 'M')))

In [67]:
# Get statistics of new column as a sanity check
loan_data['mths_since_hardship_start_date_dt'].describe()

count    10613.000000
mean        33.985207
std          6.324069
min         22.000000
25%         28.000000
50%         37.000000
75%         39.000000
max         47.000000
Name: mths_since_hardship_start_date_dt, dtype: float64

>- hardship_end_date

In [68]:
# check next_pymnt_d
loan_data['hardship_end_date']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260663    NaN
2260664    NaN
2260665    NaN
2260666    NaN
2260667    NaN
Name: hardship_end_date, Length: 2260668, dtype: object

In [69]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['hardship_end_date_dt'] = pd.to_datetime(loan_data['hardship_end_date'], format = '%b-%Y')

In [70]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_hardship_end_date_dt'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['hardship_end_date_dt']) / np.timedelta64(1, 'M')))

In [71]:
# Get statistics of new column as a sanity check
loan_data['mths_since_hardship_end_date_dt'].describe()

count    10613.000000
mean        31.594177
std          6.340798
min         19.000000
25%         25.000000
50%         34.000000
75%         37.000000
max         45.000000
Name: mths_since_hardship_end_date_dt, dtype: float64

>- payment_plan_start_date

In [72]:
# check next_pymnt_d
loan_data['payment_plan_start_date']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260663    NaN
2260664    NaN
2260665    NaN
2260666    NaN
2260667    NaN
Name: payment_plan_start_date, Length: 2260668, dtype: object

In [73]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['payment_plan_start_date_dt'] = pd.to_datetime(loan_data['payment_plan_start_date'], format = '%b-%Y')

In [74]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_payment_plan_start_date_dt'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['payment_plan_start_date_dt']) / np.timedelta64(1, 'M')))

In [75]:
# Get statistics of new column as a sanity check
loan_data['mths_since_payment_plan_start_date_dt'].describe()

count    10613.000000
mean        33.615095
std          6.351916
min         21.000000
25%         27.000000
50%         36.000000
75%         39.000000
max         46.000000
Name: mths_since_payment_plan_start_date_dt, dtype: float64

>- debt_settlement_flag_date

In [76]:
# check next_pymnt_d
loan_data['debt_settlement_flag_date']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260663    NaN
2260664    NaN
2260665    NaN
2260666    NaN
2260667    NaN
Name: debt_settlement_flag_date, Length: 2260668, dtype: object

In [77]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['debt_settlement_flag_date_dt'] = pd.to_datetime(loan_data['debt_settlement_flag_date'], format = '%b-%Y')

In [78]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_debt_settlement_flag_date'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['debt_settlement_flag_date_dt']) / np.timedelta64(1, 'M')))

In [79]:
# Get statistics of new column as a sanity check
loan_data['mths_since_debt_settlement_flag_date'].describe()

count    33056.000000
mean        31.565949
std          9.958556
min         22.000000
25%         25.000000
50%         29.000000
75%         35.000000
max        130.000000
Name: mths_since_debt_settlement_flag_date, dtype: float64

>- settlement_date

In [80]:
# check next_pymnt_d
loan_data['settlement_date']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
2260663    NaN
2260664    NaN
2260665    NaN
2260666    NaN
2260667    NaN
Name: settlement_date, Length: 2260668, dtype: object

In [81]:
# Assume we are now in December 2020
# Extracts the date and the time from a string variable.
loan_data['settlement_date_dt'] = pd.to_datetime(loan_data['settlement_date'], format = '%b-%Y')

In [82]:
# Compute difference between dates in months and cast to numeric and save in a new column
loan_data['mths_since_settlement_date_dt'] = round(pd.to_numeric((pd.to_datetime('2020-12-01') - loan_data['settlement_date_dt']) / np.timedelta64(1, 'M')))

In [83]:
# Get statistics of new column as a sanity check
loan_data['mths_since_settlement_date_dt'].describe()

count    33056.000000
mean        35.468145
std         11.288862
min         22.000000
25%         27.000000
50%         33.000000
75%         40.000000
max        141.000000
Name: mths_since_settlement_date_dt, dtype: float64

In [84]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,last_pymnt_d_date,mths_since_last_pymnt_d,next_pymnt_d_date,mths_since_next_pymnt_d,last_credit_pull_d_date,mths_since_last_credit_pull_d,sec_app_earliest_cr_line_date,mths_since_sec_app_earliest_cr_line,hardship_start_date_dt,mths_since_hardship_start_date_dt,hardship_end_date_dt,mths_since_hardship_end_date_dt,payment_plan_start_date_dt,mths_since_payment_plan_start_date_dt,debt_settlement_flag_date_dt,mths_since_debt_settlement_flag_date,settlement_date_dt,mths_since_settlement_date_dt
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2001-04-01,200.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1987-06-01,366.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2011-04-01,80.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2006-02-01,142.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2000-12-01,204.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

There are several discrete variables:

1. grade
2. sub_grade
3. home_ownership 
4. verification_status 
5. loan_status 
6. purpose 
7. addr_state 
8. initial_list_status.

# Processing discrete features

In [85]:
# Displays column names, complete (non-missing) cases per column, and datatype per column.

loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 169 entries, id to mths_since_settlement_date_dt
dtypes: datetime64[ns](11), float64(117), int64(5), object(36)
memory usage: 2.8+ GB

In [86]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,last_pymnt_d_date,mths_since_last_pymnt_d,next_pymnt_d_date,mths_since_next_pymnt_d,last_credit_pull_d_date,mths_since_last_credit_pull_d,sec_app_earliest_cr_line_date,mths_since_sec_app_earliest_cr_line,hardship_start_date_dt,mths_since_hardship_start_date_dt,hardship_end_date_dt,mths_since_hardship_end_date_dt,payment_plan_start_date_dt,mths_since_payment_plan_start_date_dt,debt_settlement_flag_date_dt,mths_since_debt_settlement_flag_date,settlement_date_dt,mths_since_settlement_date_dt
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2001-04-01,200.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1987-06-01,366.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2011-04-01,80.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,NaN,NaN,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,NaN,5.0,NaN,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2006-02-01,142.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,NaN,NaN,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,NaN,13.0,NaN,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2000-12-01,204.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-03-01,21.0,2019-02-01,22.0,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN

In [87]:
loan_data['grade'].unique()

array(['C', 'D', 'B', 'A', 'E', 'F', 'G'], dtype=object)

In [88]:
# pd.get_dummies does one-hot encoding for a column with discrete values
pd.get_dummies(loan_data['grade'])

         A  B  C  D  E  F  G
0        0  0  1  0  0  0  0
1        0  0  0  1  0  0  0
2        0  0  0  1  0  0  0
3        0  0  0  1  0  0  0
4        0  0  1  0  0  0  0
...     .. .. .. .. .. .. ..
2260663  0  0  1  0  0  0  0
2260664  0  0  0  0  1  0  0
2260665  0  1  0  0  0  0  0
2260666  0  0  0  1  0  0  0
2260667  0  0  0  1  0  0  0

[2260668 rows x 7 columns]

The column names assigned to dummy columns are meaningless.
Let us give them some meaningful names

In [89]:
# using prefix and prefix_sep parameters allows giving columns a meaningful name
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':')

         grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
0              0        0        1        0        0        0        0
1              0        0        0        1        0        0        0
2              0        0        0        1        0        0        0
3              0        0        0        1        0        0        0
4              0        0        1        0        0        0        0
...          ...      ...      ...      ...      ...      ...      ...
2260663        0        0        1        0        0        0        0
2260664        0        0        0        0        1        0        0
2260665        0        1        0        0        0        0        0
2260666        0        0        0        1        0        0        0
2260667        0        0        0        1        0        0        0

[2260668 rows x 7 columns]

In [90]:
# Repeat the above code for all discrete features
# Code below creates a dummy variable for each discrete feature and saves it to a list
# Naming convention for dummy variables is <feature name>: value

loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]

In [91]:
# Join the elements of the list to create a dataframe
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [92]:
# sanity check
type (loan_data_dummies)

pandas.core.frame.DataFrame

In [93]:
# Join the above dataframe with the original dataframe
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [94]:
# Sanity check
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'revol_bal_joint',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag',
       'hardship_type', 'hardship_reason', 'hardship_status',
       'deferral_term', 'hardship_amount', 'hardship_start_date',
       'hardship_end_date', 'payment_plan_start_date', 'hardship_length',
       'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status',
       'settlement_date', 'settlement_amount', 'settlement_percentage',
       'settlement_term', 'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'term_int', 'issue_d_date',
       'mths_since_issue_d', 'last_pymnt_d_date',
       'mths_since_last_pymnt_d', 'next_pymnt_d_date',
       'mths_since_next_pymnt_d', 'last_credit_pull_d_date',
       'mths_since_last_credit_pull_d', 'sec_app_earliest_cr_line_date',
       'mths_since_sec_app_earliest_cr_line', 'hardship_start_date_dt',
       'mths_since_hardship_start_date_dt', 'hardship_end_date_dt',
       'mths_since_hardship_end_date_dt', 'payment_plan_start_date_dt',
       'mths_since_payment_plan_start_date_dt',
       'debt_settlement_flag_date_dt',
       'mths_since_debt_settlement_flag_date', 'settlement_date_dt',
       'mths_since_settlement_date_dt', 'grade:A', 'grade:B', 'grade:C',
       'grade:D', 'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1',
       'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5',
       'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4',
       'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3',
       'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2',
       'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1',
       'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5',
       'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4',
       'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3',
       'sub_grade:G4', 'sub_grade:G5', 'home_ownership:ANY',
       'home_ownership:MORTGAGE', 'home_ownership:NONE',
       'home_ownership:OTHER', 'home_ownership:OWN',
       'home_ownership:RENT', 'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Does not meet the credit policy. Status:Charged Off',
       'loan_status:Does not meet the credit policy. Status:Fully Paid',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IA', 'addr_state:ID', 'addr_state:IL', 'addr_state:IN',
       'addr_state:KS', 'addr_state:KY', 'addr_state:LA', 'addr_state:MA',
       'addr_state:MD', 'addr_state:ME', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MS', 'addr_state:MT', 'addr_state:NC',
       'addr_state:ND', 'addr_state:NE', 'addr_state:NH', 'addr_state:NJ',
       'addr_state:NM', 'addr_state:NV', 'addr_state:NY', 'addr_state:OH',
       'addr_state:OK', 'addr_state:OR', 'addr_state:PA', 'addr_state:RI',
       'addr_state:SC', 'addr_state:SD', 'addr_state:TN', 'addr_state:TX',
       'addr_state:UT', 'addr_state:VA', 'addr_state:VT', 'addr_state:WA',
       'addr_state:WI', 'addr_state:WV', 'addr_state:WY',
       'initial_list_status:f', 'initial_list_status:w'], dtype=object)

In [95]:
# Sanity check

loan_data.shape

(2260668, 296)

More discrete features needs to be evaluated and changed 

>- application_type (individual, joint app) 
>- hardship_reason (9 values)
>- hardship_status (active broken completed)
>- hardship_loan_status (current, in grace, late(16-30), late(31-120)
>- disbursement_method (cash, direct pay)
>- settlement_status (active, broken, complete)

In [96]:
# Repeat the above code for all discrete features
# Code below creates a dummy variable for each discrete feature and saves it to a list
# Naming convention for dummy variables is <feature name>: value

loan_data_dummies = [pd.get_dummies(loan_data['application_type'], prefix = 'application_type', prefix_sep = ':'),
                     pd.get_dummies(loan_data['hardship_reason'], prefix = 'hardship_reason', prefix_sep = ':'),
                     pd.get_dummies(loan_data['hardship_status'], prefix = 'hardship_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['hardship_loan_status'], prefix = 'hardship_loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['disbursement_method'], prefix = 'disbursement_method', prefix_sep = ':'),
                     pd.get_dummies(loan_data['settlement_status'], prefix = 'settlement_status', prefix_sep = ':')]

In [97]:
# Join the elements of the list to create a dataframe
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [98]:
# sanity check
type (loan_data_dummies)

pandas.core.frame.DataFrame

In [99]:
# Join the above dataframe with the original dataframe
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [100]:
# Sanity check
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'revol_bal_joint',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag',
       'hardship_type', 'hardship_reason', 'hardship_status',
       'deferral_term', 'hardship_amount', 'hardship_start_date',
       'hardship_end_date', 'payment_plan_start_date', 'hardship_length',
       'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status',
       'settlement_date', 'settlement_amount', 'settlement_percentage',
       'settlement_term', 'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'term_int', 'issue_d_date',
       'mths_since_issue_d', 'last_pymnt_d_date',
       'mths_since_last_pymnt_d', 'next_pymnt_d_date',
       'mths_since_next_pymnt_d', 'last_credit_pull_d_date',
       'mths_since_last_credit_pull_d', 'sec_app_earliest_cr_line_date',
       'mths_since_sec_app_earliest_cr_line', 'hardship_start_date_dt',
       'mths_since_hardship_start_date_dt', 'hardship_end_date_dt',
       'mths_since_hardship_end_date_dt', 'payment_plan_start_date_dt',
       'mths_since_payment_plan_start_date_dt',
       'debt_settlement_flag_date_dt',
       'mths_since_debt_settlement_flag_date', 'settlement_date_dt',
       'mths_since_settlement_date_dt', 'grade:A', 'grade:B', 'grade:C',
       'grade:D', 'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1',
       'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5',
       'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4',
       'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3',
       'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2',
       'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1',
       'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5',
       'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4',
       'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3',
       'sub_grade:G4', 'sub_grade:G5', 'home_ownership:ANY',
       'home_ownership:MORTGAGE', 'home_ownership:NONE',
       'home_ownership:OTHER', 'home_ownership:OWN',
       'home_ownership:RENT', 'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Does not meet the credit policy. Status:Charged Off',
       'loan_status:Does not meet the credit policy. Status:Fully Paid',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IA', 'addr_state:ID', 'addr_state:IL', 'addr_state:IN',
       'addr_state:KS', 'addr_state:KY', 'addr_state:LA', 'addr_state:MA',
       'addr_state:MD', 'addr_state:ME', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MS', 'addr_state:MT', 'addr_state:NC',
       'addr_state:ND', 'addr_state:NE', 'addr_state:NH', 'addr_state:NJ',
       'addr_state:NM', 'addr_state:NV', 'addr_state:NY', 'addr_state:OH',
       'addr_state:OK', 'addr_state:OR', 'addr_state:PA', 'addr_state:RI',
       'addr_state:SC', 'addr_state:SD', 'addr_state:TN', 'addr_state:TX',
       'addr_state:UT', 'addr_state:VA', 'addr_state:VT', 'addr_state:WA',
       'addr_state:WI', 'addr_state:WV', 'addr_state:WY',
       'initial_list_status:f', 'initial_list_status:w',
       'application_type:Individual', 'application_type:Joint App',
       'hardship_reason:DISABILITY', 'hardship_reason:DIVORCE',
       'hardship_reason:EXCESSIVE_OBLIGATIONS',
       'hardship_reason:FAMILY_DEATH',
       'hardship_reason:INCOME_CURTAILMENT', 'hardship_reason:MEDICAL',
       'hardship_reason:NATURAL_DISASTER',
       'hardship_reason:REDUCED_HOURS', 'hardship_reason:UNEMPLOYMENT',
       'hardship_status:ACTIVE', 'hardship_status:BROKEN',
       'hardship_status:COMPLETED', 'hardship_loan_status:Current',
       'hardship_loan_status:In Grace Period',
       'hardship_loan_status:Issued',
       'hardship_loan_status:Late (16-30 days)',
       'hardship_loan_status:Late (31-120 days)',
       'disbursement_method:Cash', 'disbursement_method:DirectPay',
       'settlement_status:ACTIVE', 'settlement_status:BROKEN',
       'settlement_status:COMPLETE'], dtype=object)

In [101]:
# Sanity check

loan_data.shape

(2260668, 320)

>- pymnt_plan (n)
>- verification_status_joint (verified, not verified, nans)
>- hardship_flag (Y and N)
>- hardship_type (only one, and NANs)
>- debt_settlement_flag (y)

In [102]:
loan_data['pymnt_plan'].value_counts()

n    2259986
y        682
Name: pymnt_plan, dtype: int64

In [103]:
loan_data['verification_status_joint'].value_counts()

Not Verified       57403
Source Verified    34827
Verified           23500
Name: verification_status_joint, dtype: int64

In [104]:
loan_data['hardship_flag'].value_counts()

N    2259783
Y        885
Name: hardship_flag, dtype: int64

In [105]:
loan_data['hardship_type'].value_counts()

INTEREST ONLY-3 MONTHS DEFERRAL    10613
Name: hardship_type, dtype: int64

In [106]:
loan_data['debt_settlement_flag'].value_counts()

N    2227612
Y      33056
Name: debt_settlement_flag, dtype: int64

In [107]:
loan_data.replace({'pymnt_plan': {'n': 0, 'y': 1}, 'verification_status_joint': {'Not Verified': 0, 'Source Verified': 1, 'Verified': 2}, 'hardship_flag': {'N': 0, 'Y': 1}, 'hardship_type': {'INTEREST ONLY-3 MONTHS DEFERRAL': 1}, 'debt_settlement_flag': {'N': 0, 'Y': 1}},inplace=True)

# Processing missing values

In [108]:
# Look at total_rev_hi_lim. it has 70276 nulls
loan_data['total_rev_hi_lim'].isnull().sum()

70276

In [109]:
# funded_amnt does not have any missing values
loan_data['funded_amnt'].isnull().sum()

0

Total revolving high credit is another name for credit limit, so it makes sense to replace the missing values with funded_amt.
This is an example of very domain knowledge\experience is helpful.
A good data scientist must know when he\she should consult a domain expert.

In [110]:
# Replace missing values in total_rev_hi_lim with values from 
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace=True)

In [111]:
# sanity check
loan_data['total_rev_hi_lim'].isnull().sum()

0

In [112]:
# solution for 1
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)

In [113]:
# Sets the pandas dataframe options to display all columns/ rows.
pd.options.display.max_rows = None
loan_data.isnull().sum()

id                                                                 2260668
member_id                                                          2260668
loan_amnt                                                                0
funded_amnt                                                              0
funded_amnt_inv                                                          0
term                                                                     0
int_rate                                                                 0
installment                                                              0
grade                                                                    0
sub_grade                                                                0
emp_title                                                           166969
emp_length                                                          146907
home_ownership                                                           0
annual_inc                                                               0
verification_status                                                      0
issue_d                                                                  0
loan_status                                                              0
pymnt_plan                                                               0
url                                                                2260668
desc                                                               2134601
purpose                                                                  0
title                                                                23325
zip_code                                                                 1
addr_state                                                               0
dti                                                                   1711
delinq_2yrs                                                             29
earliest_cr_line                                                        29
inq_last_6mths                                                          30
mths_since_last_delinq                                             1158502
mths_since_last_record                                             1901512
open_acc                                                                29
pub_rec                                                                 29
revol_bal                                                                0
revol_util                                                            1802
total_acc                                                               29
initial_list_status                                                      0
out_prncp                                                                0
out_prncp_inv                                                            0
total_pymnt                                                              0
total_pymnt_inv                                                          0
total_rec_prncp                                                          0
total_rec_int                                                            0
total_rec_late_fee                                                       0
recoveries                                                               0
collection_recovery_fee                                                  0
last_pymnt_d                                                          2426
last_pymnt_amnt                                                          0
next_pymnt_d                                                       1303607
last_credit_pull_d                                                      73
collections_12_mths_ex_med                                             145
mths_since_last_major_derog                                        1679893
policy_code                                                              0
application_type                                                         0
annual_inc_joint                                                   2139958
dti_joint                                                          2139962
verification_status_joint                                          2144938
acc_now_delinq                                                          29
tot_coll_amt                                                         70276
tot_cur_bal                                                          70276
open_acc_6m                                                         866130
open_act_il                                                         866129
open_il_12m                                                         866129
open_il_24m                                                         866129
mths_since_rcnt_il                                                  909924
total_bal_il                                                        866129
il_util                                                            1068850
open_rv_12m                                                         866129
open_rv_24m                                                         866129
max_bal_bc                                                          866129
all_util                                                            866348
total_rev_hi_lim                                                         0
inq_fi                                                              866129
total_cu_tl                                                         866130
inq_last_12m                                                        866130
acc_open_past_24mths                                                 50030
avg_cur_bal                                                          70346
bc_open_to_buy                                                       74935
bc_util                                                              76071
chargeoff_within_12_mths                                               145
delinq_amnt                                                             29
mo_sin_old_il_acct                                                  139071
mo_sin_old_rev_tl_op                                                 70277
mo_sin_rcnt_rev_tl_op                                                70277
mo_sin_rcnt_tl                                                       70276
mort_acc                                                             50030
mths_since_recent_bc                                                 73412
mths_since_recent_bc_dlq                                           1740967
mths_since_recent_inq                                               295435
mths_since_recent_revol_delinq                                     1520309
num_accts_ever_120_pd                                                70276
num_actv_bc_tl                                                       70276
num_actv_rev_tl                                                      70276
num_bc_sats                                                          58590
num_bc_tl                                                            70276
num_il_tl                                                            70276
num_op_rev_tl                                                        70276
num_rev_accts                                                        70277
num_rev_tl_bal_gt_0                                                  70276
num_sats                                                             58590
num_tl_120dpd_2m                                                    153657
num_tl_30dpd                                                         70276
num_tl_90g_dpd_24m                                                   70276
num_tl_op_past_12m                                                   70276
pct_tl_nvr_dlq                                                       70431
percent_bc_gt_75                                                     75379
pub_rec_bankruptcies                                                  1365
tax_liens                                                              105
tot_hi_cred_lim                                                      70276
total_bal_ex_mort                                                    50030
total_bc_limit                                                       50030
total_il_high_credit_limit                                           70276
revol_bal_joint                                                    2152648
sec_app_earliest_cr_line                                           2152647
sec_app_inq_last_6mths                                             2152647
sec_app_mort_acc                                                   2152647
sec_app_open_acc                                                   2152647
sec_app_revol_util                                                 2154484
sec_app_open_act_il                                                2152647
sec_app_num_rev_accts                                              2152647
sec_app_chargeoff_within_12_mths                                   2152647
sec_app_collections_12_mths_ex_med                                 2152647
sec_app_mths_since_last_major_derog                                2224726
hardship_flag                                                            0
hardship_type                                                      2250055
hardship_reason                                                    2250055
hardship_status                                                    2250055
deferral_term                                                      2250055
hardship_amount                                                    2250055
hardship_start_date                                                2250055
hardship_end_date                                                  2250055
payment_plan_start_date                                            2250055
hardship_length                                                    2250055
hardship_dpd                                                       2250055
hardship_loan_status                                               2250055
orig_projected_additional_accrued_interest                         2252242
hardship_payoff_balance_amount                                     2250055
hardship_last_payment_amount                                       2250055
disbursement_method                                                      0
debt_settlement_flag                                                     0
debt_settlement_flag_date                                          2227612
settlement_status                                                  2227612
settlement_date                                                    2227612
settlement_amount                                                  2227612
settlement_percentage                                              2227612
settlement_term                                                    2227612
emp_length_int                                                      146907
earliest_cr_line_date                                                   29
mths_since_earliest_cr_line                                             29
term_int                                                                 0
issue_d_date                                                             0
mths_since_issue_d                                                       0
last_pymnt_d_date                                                     2426
mths_since_last_pymnt_d                                               2426
next_pymnt_d_date                                                  1303607
mths_since_next_pymnt_d                                            1303607
last_credit_pull_d_date                                                 73
mths_since_last_credit_pull_d                                           73
sec_app_earliest_cr_line_date                                      2152647
mths_since_sec_app_earliest_cr_line                                2152647
hardship_start_date_dt                                             2250055
mths_since_hardship_start_date_dt                                  2250055
hardship_end_date_dt                                               2250055
mths_since_hardship_end_date_dt                                    2250055
payment_plan_start_date_dt                                         2250055
mths_since_payment_plan_start_date_dt                              2250055
debt_settlement_flag_date_dt                                       2227612
mths_since_debt_settlement_flag_date                               2227612
settlement_date_dt                                                 2227612
mths_since_settlement_date_dt                                      2227612
grade:A                                                                  0
grade:B                                                                  0
grade:C                                                                  0
grade:D                                                                  0
grade:E                                                                  0
grade:F                                                                  0
grade:G                                                                  0
sub_grade:A1                                                             0
sub_grade:A2                                                             0
sub_grade:A3                                                             0
sub_grade:A4                                                             0
sub_grade:A5                                                             0
sub_grade:B1                                                             0
sub_grade:B2                                                             0
sub_grade:B3                                                             0
sub_grade:B4                                                             0
sub_grade:B5                                                             0
sub_grade:C1                                                             0
sub_grade:C2                                                             0
sub_grade:C3                                                             0
sub_grade:C4                                                             0
sub_grade:C5                                                             0
sub_grade:D1                                                             0
sub_grade:D2                                                             0
sub_grade:D3                                                             0
sub_grade:D4                                                             0
sub_grade:D5                                                             0
sub_grade:E1                                                             0
sub_grade:E2                                                             0
sub_grade:E3                                                             0
sub_grade:E4                                                             0
sub_grade:E5                                                             0
sub_grade:F1                                                             0
sub_grade:F2                                                             0
sub_grade:F3                                                             0
sub_grade:F4                                                             0
sub_grade:F5                                                             0
sub_grade:G1                                                             0
sub_grade:G2                                                             0
sub_grade:G3                                                             0
sub_grade:G4                                                             0
sub_grade:G5                                                             0
home_ownership:ANY                                                       0
home_ownership:MORTGAGE                                                  0
home_ownership:NONE                                                      0
home_ownership:OTHER                                                     0
home_ownership:OWN                                                       0
home_ownership:RENT                                                      0
verification_status:Not Verified                                         0
verification_status:Source Verified                                      0
verification_status:Verified                                             0
loan_status:Charged Off                                                  0
loan_status:Current                                                      0
loan_status:Default                                                      0
loan_status:Does not meet the credit policy. Status:Charged Off          0
loan_status:Does not meet the credit policy. Status:Fully Paid           0
loan_status:Fully Paid                                                   0
loan_status:In Grace Period                                              0
loan_status:Late (16-30 days)                                            0
loan_status:Late (31-120 days)                                           0
purpose:car                                                              0
purpose:credit_card                                                      0
purpose:debt_consolidation                                               0
purpose:educational                                                      0
purpose:home_improvement                                                 0
purpose:house                                                            0
purpose:major_purchase                                                   0
purpose:medical                                                          0
purpose:moving                                                           0
purpose:other                                                            0
purpose:renewable_energy                                                 0
purpose:small_business                                                   0
purpose:vacation                                                         0
purpose:wedding                                                          0
addr_state:AK                                                            0
addr_state:AL                                                            0
addr_state:AR                                                            0
addr_state:AZ                                                            0
addr_state:CA                                                            0
addr_state:CO                                                            0
addr_state:CT                                                            0
addr_state:DC                                                            0
addr_state:DE                                                            0
addr_state:FL                                                            0
addr_state:GA                                                            0
addr_state:HI                                                            0
addr_state:IA                                                            0
addr_state:ID                                                            0
addr_state:IL                                                            0
addr_state:IN                                                            0
addr_state:KS                                                            0
addr_state:KY                                                            0
addr_state:LA                                                            0
addr_state:MA                                                            0
addr_state:MD                                                            0
addr_state:ME                                                            0
addr_state:MI                                                            0

In [114]:
# funcion to get null value
def column_wise_null_percentage(df):
    output = round(df.isnull().sum()/len(df.index)*100,2)
    return output

In [115]:
# get missign values of all columns
NA_col = column_wise_null_percentage(loan_data)
NA_col

id                                                                 100.00
member_id                                                          100.00
loan_amnt                                                            0.00
funded_amnt                                                          0.00
funded_amnt_inv                                                      0.00
term                                                                 0.00
int_rate                                                             0.00
installment                                                          0.00
grade                                                                0.00
sub_grade                                                            0.00
emp_title                                                            7.39
emp_length                                                           6.50
home_ownership                                                       0.00
annual_inc                                                           0.00
verification_status                                                  0.00
issue_d                                                              0.00
loan_status                                                          0.00
pymnt_plan                                                           0.00
url                                                                100.00
desc                                                                94.42
purpose                                                              0.00
title                                                                1.03
zip_code                                                             0.00
addr_state                                                           0.00
dti                                                                  0.08
delinq_2yrs                                                          0.00
earliest_cr_line                                                     0.00
inq_last_6mths                                                       0.00
mths_since_last_delinq                                              51.25
mths_since_last_record                                              84.11
open_acc                                                             0.00
pub_rec                                                              0.00
revol_bal                                                            0.00
revol_util                                                           0.08
total_acc                                                            0.00
initial_list_status                                                  0.00
out_prncp                                                            0.00
out_prncp_inv                                                        0.00
total_pymnt                                                          0.00
total_pymnt_inv                                                      0.00
total_rec_prncp                                                      0.00
total_rec_int                                                        0.00
total_rec_late_fee                                                   0.00
recoveries                                                           0.00
collection_recovery_fee                                              0.00
last_pymnt_d                                                         0.11
last_pymnt_amnt                                                      0.00
next_pymnt_d                                                        57.66
last_credit_pull_d                                                   0.00
collections_12_mths_ex_med                                           0.01
mths_since_last_major_derog                                         74.31
policy_code                                                          0.00
application_type                                                     0.00
annual_inc_joint                                                    94.66
dti_joint                                                           94.66
verification_status_joint                                           94.88
acc_now_delinq                                                       0.00
tot_coll_amt                                                         3.11
tot_cur_bal                                                          3.11
open_acc_6m                                                         38.31
open_act_il                                                         38.31
open_il_12m                                                         38.31
open_il_24m                                                         38.31
mths_since_rcnt_il                                                  40.25
total_bal_il                                                        38.31
il_util                                                             47.28
open_rv_12m                                                         38.31
open_rv_24m                                                         38.31
max_bal_bc                                                          38.31
all_util                                                            38.32
total_rev_hi_lim                                                     0.00
inq_fi                                                              38.31
total_cu_tl                                                         38.31
inq_last_12m                                                        38.31
acc_open_past_24mths                                                 2.21
avg_cur_bal                                                          3.11
bc_open_to_buy                                                       3.31
bc_util                                                              3.36
chargeoff_within_12_mths                                             0.01
delinq_amnt                                                          0.00
mo_sin_old_il_acct                                                   6.15
mo_sin_old_rev_tl_op                                                 3.11
mo_sin_rcnt_rev_tl_op                                                3.11
mo_sin_rcnt_tl                                                       3.11
mort_acc                                                             2.21
mths_since_recent_bc                                                 3.25
mths_since_recent_bc_dlq                                            77.01
mths_since_recent_inq                                               13.07
mths_since_recent_revol_delinq                                      67.25
num_accts_ever_120_pd                                                3.11
num_actv_bc_tl                                                       3.11
num_actv_rev_tl                                                      3.11
num_bc_sats                                                          2.59
num_bc_tl                                                            3.11
num_il_tl                                                            3.11
num_op_rev_tl                                                        3.11
num_rev_accts                                                        3.11
num_rev_tl_bal_gt_0                                                  3.11
num_sats                                                             2.59
num_tl_120dpd_2m                                                     6.80
num_tl_30dpd                                                         3.11
num_tl_90g_dpd_24m                                                   3.11
num_tl_op_past_12m                                                   3.11
pct_tl_nvr_dlq                                                       3.12
percent_bc_gt_75                                                     3.33
pub_rec_bankruptcies                                                 0.06
tax_liens                                                            0.00
tot_hi_cred_lim                                                      3.11
total_bal_ex_mort                                                    2.21
total_bc_limit                                                       2.21
total_il_high_credit_limit                                           3.11
revol_bal_joint                                                     95.22
sec_app_earliest_cr_line                                            95.22
sec_app_inq_last_6mths                                              95.22
sec_app_mort_acc                                                    95.22
sec_app_open_acc                                                    95.22
sec_app_revol_util                                                  95.30
sec_app_open_act_il                                                 95.22
sec_app_num_rev_accts                                               95.22
sec_app_chargeoff_within_12_mths                                    95.22
sec_app_collections_12_mths_ex_med                                  95.22
sec_app_mths_since_last_major_derog                                 98.41
hardship_flag                                                        0.00
hardship_type                                                       99.53
hardship_reason                                                     99.53
hardship_status                                                     99.53
deferral_term                                                       99.53
hardship_amount                                                     99.53
hardship_start_date                                                 99.53
hardship_end_date                                                   99.53
payment_plan_start_date                                             99.53
hardship_length                                                     99.53
hardship_dpd                                                        99.53
hardship_loan_status                                                99.53
orig_projected_additional_accrued_interest                          99.63
hardship_payoff_balance_amount                                      99.53
hardship_last_payment_amount                                        99.53
disbursement_method                                                  0.00
debt_settlement_flag                                                 0.00
debt_settlement_flag_date                                           98.54
settlement_status                                                   98.54
settlement_date                                                     98.54
settlement_amount                                                   98.54
settlement_percentage                                               98.54
settlement_term                                                     98.54
emp_length_int                                                       6.50
earliest_cr_line_date                                                0.00
mths_since_earliest_cr_line                                          0.00
term_int                                                             0.00
issue_d_date                                                         0.00
mths_since_issue_d                                                   0.00
last_pymnt_d_date                                                    0.11
mths_since_last_pymnt_d                                              0.11
next_pymnt_d_date                                                   57.66
mths_since_next_pymnt_d                                             57.66
last_credit_pull_d_date                                              0.00
mths_since_last_credit_pull_d                                        0.00
sec_app_earliest_cr_line_date                                       95.22
mths_since_sec_app_earliest_cr_line                                 95.22
hardship_start_date_dt                                              99.53
mths_since_hardship_start_date_dt                                   99.53
hardship_end_date_dt                                                99.53
mths_since_hardship_end_date_dt                                     99.53
payment_plan_start_date_dt                                          99.53
mths_since_payment_plan_start_date_dt                               99.53
debt_settlement_flag_date_dt                                        98.54
mths_since_debt_settlement_flag_date                                98.54
settlement_date_dt                                                  98.54
mths_since_settlement_date_dt                                       98.54
grade:A                                                              0.00
grade:B                                                              0.00
grade:C                                                              0.00
grade:D                                                              0.00
grade:E                                                              0.00
grade:F                                                              0.00
grade:G                                                              0.00
sub_grade:A1                                                         0.00
sub_grade:A2                                                         0.00
sub_grade:A3                                                         0.00
sub_grade:A4                                                         0.00
sub_grade:A5                                                         0.00
sub_grade:B1                                                         0.00
sub_grade:B2                                                         0.00
sub_grade:B3                                                         0.00
sub_grade:B4                                                         0.00
sub_grade:B5                                                         0.00
sub_grade:C1                                                         0.00
sub_grade:C2                                                         0.00
sub_grade:C3                                                         0.00
sub_grade:C4                                                         0.00
sub_grade:C5                                                         0.00
sub_grade:D1                                                         0.00
sub_grade:D2                                                         0.00
sub_grade:D3                                                         0.00
sub_grade:D4                                                         0.00
sub_grade:D5                                                         0.00
sub_grade:E1                                                         0.00
sub_grade:E2                                                         0.00
sub_grade:E3                                                         0.00
sub_grade:E4                                                         0.00
sub_grade:E5                                                         0.00
sub_grade:F1                                                         0.00
sub_grade:F2                                                         0.00
sub_grade:F3                                                         0.00
sub_grade:F4                                                         0.00
sub_grade:F5                                                         0.00
sub_grade:G1                                                         0.00
sub_grade:G2                                                         0.00
sub_grade:G3                                                         0.00
sub_grade:G4                                                         0.00
sub_grade:G5                                                         0.00
home_ownership:ANY                                                   0.00
home_ownership:MORTGAGE                                              0.00
home_ownership:NONE                                                  0.00
home_ownership:OTHER                                                 0.00
home_ownership:OWN                                                   0.00
home_ownership:RENT                                                  0.00
verification_status:Not Verified                                     0.00
verification_status:Source Verified                                  0.00
verification_status:Verified                                         0.00
loan_status:Charged Off                                              0.00
loan_status:Current                                                  0.00
loan_status:Default                                                  0.00
loan_status:Does not meet the credit policy. Status:Charged Off      0.00
loan_status:Does not meet the credit policy. Status:Fully Paid       0.00
loan_status:Fully Paid                                               0.00
loan_status:In Grace Period                                          0.00
loan_status:Late (16-30 days)                                        0.00
loan_status:Late (31-120 days)                                       0.00
purpose:car                                                          0.00
purpose:credit_card                                                  0.00
purpose:debt_consolidation                                           0.00
purpose:educational                                                  0.00
purpose:home_improvement                                             0.00
purpose:house                                                        0.00
purpose:major_purchase                                               0.00
purpose:medical                                                      0.00
purpose:moving                                                       0.00
purpose:other                                                        0.00
purpose:renewable_energy                                             0.00
purpose:small_business                                               0.00
purpose:vacation                                                     0.00
purpose:wedding                                                      0.00
addr_state:AK                                                        0.00
addr_state:AL                                                        0.00
addr_state:AR                                                        0.00
addr_state:AZ                                                        0.00
addr_state:CA                                                        0.00
addr_state:CO                                                        0.00
addr_state:CT                                                        0.00
addr_state:DC                                                        0.00
addr_state:DE                                                        0.00
addr_state:FL                                                        0.00
addr_state:GA                                                        0.00
addr_state:HI                                                        0.00
addr_state:IA                                                        0.00
addr_state:ID                                                        0.00
addr_state:IL                                                        0.00
addr_state:IN                                                        0.00
addr_state:KS                                                        0.00
addr_state:KY                                                        0.00
addr_state:LA                                                        0.00
addr_state:MA                                                        0.00
addr_state:MD                                                        0.00
addr_state:ME                                                        0.00
addr_state:MI                                                        0.00
addr_state:MN                                                        0.00
addr_state:MO                                                        0.00
addr_state:MS                                                        0.00
addr_state:MT                                                        0.00

In [116]:
NA_col_50 = NA_col[NA_col>50]
print("Number of columns having null value more than 50% :", len(NA_col_50.index))
print(NA_col_50)

Number of columns having null value more than 50% : 58
id                                            100.00
member_id                                     100.00
url                                           100.00
desc                                           94.42
mths_since_last_delinq                         51.25
mths_since_last_record                         84.11
next_pymnt_d                                   57.66
mths_since_last_major_derog                    74.31
annual_inc_joint                               94.66
dti_joint                                      94.66
verification_status_joint                      94.88
mths_since_recent_bc_dlq                       77.01
mths_since_recent_revol_delinq                 67.25
revol_bal_joint                                95.22
sec_app_earliest_cr_line                       95.22
sec_app_inq_last_6mths                         95.22
sec_app_mort_acc                               95.22
sec_app_open_acc                               95.22
sec_app_revol_util                             95.30
sec_app_open_act_il                            95.22
sec_app_num_rev_accts                          95.22
sec_app_chargeoff_within_12_mths               95.22
sec_app_collections_12_mths_ex_med             95.22
sec_app_mths_since_last_major_derog            98.41
hardship_type                                  99.53
hardship_reason                                99.53
hardship_status                                99.53
deferral_term                                  99.53
hardship_amount                                99.53
hardship_start_date                            99.53
hardship_end_date                              99.53
payment_plan_start_date                        99.53
hardship_length                                99.53
hardship_dpd                                   99.53
hardship_loan_status                           99.53
orig_projected_additional_accrued_interest     99.63
hardship_payoff_balance_amount                 99.53
hardship_last_payment_amount                   99.53
debt_settlement_flag_date                      98.54
settlement_status                              98.54
settlement_date                                98.54
settlement_amount                              98.54
settlement_percentage                          98.54
settlement_term                                98.54
next_pymnt_d_date                              57.66
mths_since_next_pymnt_d                        57.66
sec_app_earliest_cr_line_date                  95.22
mths_since_sec_app_earliest_cr_line            95.22
hardship_start_date_dt                         99.53
mths_since_hardship_start_date_dt              99.53
hardship_end_date_dt                           99.53
mths_since_hardship_end_date_dt                99.53
payment_plan_start_date_dt                     99.53
mths_since_payment_plan_start_date_dt          99.53
debt_settlement_flag_date_dt                   98.54
mths_since_debt_settlement_flag_date           98.54
settlement_date_dt                             98.54
mths_since_settlement_date_dt                  98.54
dtype: float64

In [117]:
# removed 58 columns having null percentage more than 50%.
loan_data = loan_data.drop(NA_col_50.index, axis =1)
loan_data.shape

(2260668, 262)

In [118]:
loan_data.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,last_pymnt_d_date,mths_since_last_pymnt_d,last_credit_pull_d_date,mths_since_last_credit_pull_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w,application_type:Individual,application_type:Joint App,hardship_reason:DISABILITY,hardship_reason:DIVORCE,hardship_reason:EXCESSIVE_OBLIGATIONS,hardship_reason:FAMILY_DEATH,hardship_reason:INCOME_CURTAILMENT,hardship_reason:MEDICAL,hardship_reason:NATURAL_DISASTER,hardship_reason:REDUCED_HOURS,hardship_reason:UNEMPLOYMENT,hardship_status:ACTIVE,hardship_status:BROKEN,hardship_status:COMPLETED,hardship_loan_status:Current,hardship_loan_status:In Grace Period,hardship_loan_status:Issued,hardship_loan_status:Late (16-30 days),hardship_loan_status:Late (31-120 days),disbursement_method:Cash,disbursement_method:DirectPay,settlement_status:ACTIVE,settlement_status:BROKEN,settlement_status:COMPLETE
0,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,0,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Feb-2019,0.0,1,Individual,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,2.0,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,0,Cash,0,10.0,2001-04-01,200.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-02-01,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,0,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Feb-2019,0.0,1,Individual,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,0,Cash,0,10.0,1987-06-01,366.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-02-01,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,0,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Feb-2019,0.0,1,Individual,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,14.0,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,0,Cash,0,6.0,2011-04-01,80.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-02-01,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4000,4000,4000.0,36 months,18.94,146.51,D,D2,IT Supervisor,10+ years,MORTGAGE,92000.0,Source Verified,Dec-2018,Current,0,debt_consolidation,Debt consolidation,985xx,WA,16.74,0.0,Feb-2006,0.0,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,Feb-2019,146.51,Feb-2019,0.0,1,Individual,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,5.0,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,0,Cash,0,10.0,2006-02-01,142.0,36,2018-12-01,126.0,2019-02-01,22.0,2019-02-01,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,30000,30000,30000.0,60 months,16.14,731.78,C,C4,Mechanic,10+ years,MORTGAGE,57250.0,Not Verified,Dec-2018,Current,0,debt_consolidation,Debt consolidation,212xx,MD,26.35,0.0,Dec-2000,0.0,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,Feb-2019,731.78,Feb-2019,0.0,1,Individual,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,13.0,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,0,Cash,0,10.0,2000-12-01,204.0,60,2018-12-01,126.0,2019-02-01,22.0,2019-02-01,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [119]:
loan_data = loan_data.drop(["term","emp_title","emp_length","issue_d","title","zip_code","earliest_cr_line","last_pymnt_d","last_credit_pull_d"], axis=1)
loan_data.shape

(2260668, 253)

In [120]:
loan_data = loan_data.drop(["earliest_cr_line_date","issue_d_date","last_pymnt_d_date","last_credit_pull_d_date"], axis=1)
loan_data.shape

(2260668, 249)

In [121]:
NA_col1 = column_wise_null_percentage(loan_data)
NA_col1

loan_amnt                                                           0.00
funded_amnt                                                         0.00
funded_amnt_inv                                                     0.00
int_rate                                                            0.00
installment                                                         0.00
grade                                                               0.00
sub_grade                                                           0.00
home_ownership                                                      0.00
annual_inc                                                          0.00
verification_status                                                 0.00
loan_status                                                         0.00
pymnt_plan                                                          0.00
purpose                                                             0.00
addr_state                                                          0.00
dti                                                                 0.08
delinq_2yrs                                                         0.00
inq_last_6mths                                                      0.00
open_acc                                                            0.00
pub_rec                                                             0.00
revol_bal                                                           0.00
revol_util                                                          0.08
total_acc                                                           0.00
initial_list_status                                                 0.00
out_prncp                                                           0.00
out_prncp_inv                                                       0.00
total_pymnt                                                         0.00
total_pymnt_inv                                                     0.00
total_rec_prncp                                                     0.00
total_rec_int                                                       0.00
total_rec_late_fee                                                  0.00
recoveries                                                          0.00
collection_recovery_fee                                             0.00
last_pymnt_amnt                                                     0.00
collections_12_mths_ex_med                                          0.01
policy_code                                                         0.00
application_type                                                    0.00
acc_now_delinq                                                      0.00
tot_coll_amt                                                        3.11
tot_cur_bal                                                         3.11
open_acc_6m                                                        38.31
open_act_il                                                        38.31
open_il_12m                                                        38.31
open_il_24m                                                        38.31
mths_since_rcnt_il                                                 40.25
total_bal_il                                                       38.31
il_util                                                            47.28
open_rv_12m                                                        38.31
open_rv_24m                                                        38.31
max_bal_bc                                                         38.31
all_util                                                           38.32
total_rev_hi_lim                                                    0.00
inq_fi                                                             38.31
total_cu_tl                                                        38.31
inq_last_12m                                                       38.31
acc_open_past_24mths                                                2.21
avg_cur_bal                                                         3.11
bc_open_to_buy                                                      3.31
bc_util                                                             3.36
chargeoff_within_12_mths                                            0.01
delinq_amnt                                                         0.00
mo_sin_old_il_acct                                                  6.15
mo_sin_old_rev_tl_op                                                3.11
mo_sin_rcnt_rev_tl_op                                               3.11
mo_sin_rcnt_tl                                                      3.11
mort_acc                                                            2.21
mths_since_recent_bc                                                3.25
mths_since_recent_inq                                              13.07
num_accts_ever_120_pd                                               3.11
num_actv_bc_tl                                                      3.11
num_actv_rev_tl                                                     3.11
num_bc_sats                                                         2.59
num_bc_tl                                                           3.11
num_il_tl                                                           3.11
num_op_rev_tl                                                       3.11
num_rev_accts                                                       3.11
num_rev_tl_bal_gt_0                                                 3.11
num_sats                                                            2.59
num_tl_120dpd_2m                                                    6.80
num_tl_30dpd                                                        3.11
num_tl_90g_dpd_24m                                                  3.11
num_tl_op_past_12m                                                  3.11
pct_tl_nvr_dlq                                                      3.12
percent_bc_gt_75                                                    3.33
pub_rec_bankruptcies                                                0.06
tax_liens                                                           0.00
tot_hi_cred_lim                                                     3.11
total_bal_ex_mort                                                   2.21
total_bc_limit                                                      2.21
total_il_high_credit_limit                                          3.11
hardship_flag                                                       0.00
disbursement_method                                                 0.00
debt_settlement_flag                                                0.00
emp_length_int                                                      6.50
mths_since_earliest_cr_line                                         0.00
term_int                                                            0.00
mths_since_issue_d                                                  0.00
mths_since_last_pymnt_d                                             0.11
mths_since_last_credit_pull_d                                       0.00
grade:A                                                             0.00
grade:B                                                             0.00
grade:C                                                             0.00
grade:D                                                             0.00
grade:E                                                             0.00
grade:F                                                             0.00
grade:G                                                             0.00
sub_grade:A1                                                        0.00
sub_grade:A2                                                        0.00
sub_grade:A3                                                        0.00
sub_grade:A4                                                        0.00
sub_grade:A5                                                        0.00
sub_grade:B1                                                        0.00
sub_grade:B2                                                        0.00
sub_grade:B3                                                        0.00
sub_grade:B4                                                        0.00
sub_grade:B5                                                        0.00
sub_grade:C1                                                        0.00
sub_grade:C2                                                        0.00
sub_grade:C3                                                        0.00
sub_grade:C4                                                        0.00
sub_grade:C5                                                        0.00
sub_grade:D1                                                        0.00
sub_grade:D2                                                        0.00
sub_grade:D3                                                        0.00
sub_grade:D4                                                        0.00
sub_grade:D5                                                        0.00
sub_grade:E1                                                        0.00
sub_grade:E2                                                        0.00
sub_grade:E3                                                        0.00
sub_grade:E4                                                        0.00
sub_grade:E5                                                        0.00
sub_grade:F1                                                        0.00
sub_grade:F2                                                        0.00
sub_grade:F3                                                        0.00
sub_grade:F4                                                        0.00
sub_grade:F5                                                        0.00
sub_grade:G1                                                        0.00
sub_grade:G2                                                        0.00
sub_grade:G3                                                        0.00
sub_grade:G4                                                        0.00
sub_grade:G5                                                        0.00
home_ownership:ANY                                                  0.00
home_ownership:MORTGAGE                                             0.00
home_ownership:NONE                                                 0.00
home_ownership:OTHER                                                0.00
home_ownership:OWN                                                  0.00
home_ownership:RENT                                                 0.00
verification_status:Not Verified                                    0.00
verification_status:Source Verified                                 0.00
verification_status:Verified                                        0.00
loan_status:Charged Off                                             0.00
loan_status:Current                                                 0.00
loan_status:Default                                                 0.00
loan_status:Does not meet the credit policy. Status:Charged Off     0.00
loan_status:Does not meet the credit policy. Status:Fully Paid      0.00
loan_status:Fully Paid                                              0.00
loan_status:In Grace Period                                         0.00
loan_status:Late (16-30 days)                                       0.00
loan_status:Late (31-120 days)                                      0.00
purpose:car                                                         0.00
purpose:credit_card                                                 0.00
purpose:debt_consolidation                                          0.00
purpose:educational                                                 0.00
purpose:home_improvement                                            0.00
purpose:house                                                       0.00
purpose:major_purchase                                              0.00
purpose:medical                                                     0.00
purpose:moving                                                      0.00
purpose:other                                                       0.00
purpose:renewable_energy                                            0.00
purpose:small_business                                              0.00
purpose:vacation                                                    0.00
purpose:wedding                                                     0.00
addr_state:AK                                                       0.00
addr_state:AL                                                       0.00
addr_state:AR                                                       0.00
addr_state:AZ                                                       0.00
addr_state:CA                                                       0.00
addr_state:CO                                                       0.00
addr_state:CT                                                       0.00
addr_state:DC                                                       0.00
addr_state:DE                                                       0.00
addr_state:FL                                                       0.00
addr_state:GA                                                       0.00
addr_state:HI                                                       0.00
addr_state:IA                                                       0.00
addr_state:ID                                                       0.00
addr_state:IL                                                       0.00
addr_state:IN                                                       0.00
addr_state:KS                                                       0.00
addr_state:KY                                                       0.00
addr_state:LA                                                       0.00
addr_state:MA                                                       0.00
addr_state:MD                                                       0.00
addr_state:ME                                                       0.00
addr_state:MI                                                       0.00
addr_state:MN                                                       0.00
addr_state:MO                                                       0.00
addr_state:MS                                                       0.00
addr_state:MT                                                       0.00
addr_state:NC                                                       0.00
addr_state:ND                                                       0.00
addr_state:NE                                                       0.00
addr_state:NH                                                       0.00
addr_state:NJ                                                       0.00
addr_state:NM                                                       0.00
addr_state:NV                                                       0.00
addr_state:NY                                                       0.00
addr_state:OH                                                       0.00
addr_state:OK                                                       0.00
addr_state:OR                                                       0.00
addr_state:PA                                                       0.00
addr_state:RI                                                       0.00
addr_state:SC                                                       0.00
addr_state:SD                                                       0.00
addr_state:TN                                                       0.00
addr_state:TX                                                       0.00
addr_state:UT                                                       0.00
addr_state:VA                                                       0.00
addr_state:VT                                                       0.00
addr_state:WA                                                       0.00
addr_state:WI                                                       0.00
addr_state:WV                                                       0.00
addr_state:WY                                                       0.00
initial_list_status:f                                               0.00
initial_list_status:w                                               0.00
application_type:Individual                                         0.00
application_type:Joint App                                          0.00
hardship_reason:DISABILITY                                          0.00
hardship_reason:DIVORCE                                             0.00
hardship_reason:EXCESSIVE_OBLIGATIONS                               0.00
hardship_reason:FAMILY_DEATH                                        0.00
hardship_reason:INCOME_CURTAILMENT                                  0.00
hardship_reason:MEDICAL                                             0.00
hardship_reason:NATURAL_DISASTER                                    0.00
hardship_reason:REDUCED_HOURS                                       0.00
hardship_reason:UNEMPLOYMENT                                        0.00
hardship_status:ACTIVE                                              0.00
hardship_status:BROKEN                                              0.00
hardship_status:COMPLETED                                           0.00
hardship_loan_status:Current                                        0.00
hardship_loan_status:In Grace Period                                0.00
hardship_loan_status:Issued                                         0.00
hardship_loan_status:Late (16-30 days)                              0.00
hardship_loan_status:Late (31-120 days)                             0.00
disbursement_method:Cash                                            0.00
disbursement_method:DirectPay                                       0.00
settlement_status:ACTIVE                                            0.00
settlement_status:BROKEN                                            0.00
settlement_status:COMPLETE                                          0.00
dtype: float64

In [122]:
# identify columns only with null values
NA_col1 = NA_col1[NA_col1>0]
NA_col1

dti                            0.08
revol_util                     0.08
collections_12_mths_ex_med     0.01
tot_coll_amt                   3.11
tot_cur_bal                    3.11
open_acc_6m                   38.31
open_act_il                   38.31
open_il_12m                   38.31
open_il_24m                   38.31
mths_since_rcnt_il            40.25
total_bal_il                  38.31
il_util                       47.28
open_rv_12m                   38.31
open_rv_24m                   38.31
max_bal_bc                    38.31
all_util                      38.32
inq_fi                        38.31
total_cu_tl                   38.31
inq_last_12m                  38.31
acc_open_past_24mths           2.21
avg_cur_bal                    3.11
bc_open_to_buy                 3.31
bc_util                        3.36
chargeoff_within_12_mths       0.01
mo_sin_old_il_acct             6.15
mo_sin_old_rev_tl_op           3.11
mo_sin_rcnt_rev_tl_op          3.11
mo_sin_rcnt_tl                 3.11
mort_acc                       2.21
mths_since_recent_bc           3.25
mths_since_recent_inq         13.07
num_accts_ever_120_pd          3.11
num_actv_bc_tl                 3.11
num_actv_rev_tl                3.11
num_bc_sats                    2.59
num_bc_tl                      3.11
num_il_tl                      3.11
num_op_rev_tl                  3.11
num_rev_accts                  3.11
num_rev_tl_bal_gt_0            3.11
num_sats                       2.59
num_tl_120dpd_2m               6.80
num_tl_30dpd                   3.11
num_tl_90g_dpd_24m             3.11
num_tl_op_past_12m             3.11
pct_tl_nvr_dlq                 3.12
percent_bc_gt_75               3.33
pub_rec_bankruptcies           0.06
tot_hi_cred_lim                3.11
total_bal_ex_mort              2.21
total_bc_limit                 2.21
total_il_high_credit_limit     3.11
emp_length_int                 6.50
mths_since_last_pymnt_d        0.11
dtype: float64

In [123]:
loan_data.head()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,grade,sub_grade,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,addr_state,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_int,mths_since_earliest_cr_line,term_int,mths_since_issue_d,mths_since_last_pymnt_d,mths_since_last_credit_pull_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w,application_type:Individual,application_type:Joint App,hardship_reason:DISABILITY,hardship_reason:DIVORCE,hardship_reason:EXCESSIVE_OBLIGATIONS,hardship_reason:FAMILY_DEATH,hardship_reason:INCOME_CURTAILMENT,hardship_reason:MEDICAL,hardship_reason:NATURAL_DISASTER,hardship_reason:REDUCED_HOURS,hardship_reason:UNEMPLOYMENT,hardship_status:ACTIVE,hardship_status:BROKEN,hardship_status:COMPLETED,hardship_loan_status:Current,hardship_loan_status:In Grace Period,hardship_loan_status:Issued,hardship_loan_status:Late (16-30 days),hardship_loan_status:Late (31-120 days),disbursement_method:Cash,disbursement_method:DirectPay,settlement_status:ACTIVE,settlement_status:BROKEN,settlement_status:COMPLETE
0,2500,2500,2500.0,13.56,84.92,C,C1,RENT,55000.0,Not Verified,Current,0,debt_consolidation,NY,18.24,0.0,1.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,84.92,0.0,1,Individual,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,2.0,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,0,Cash,0,10.0,200.0,36,126.0,22.0,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,30000,30000,30000.0,18.94,777.23,D,D2,MORTGAGE,90000.0,Source Verified,Current,0,debt_consolidation,LA,26.52,0.0,0.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,777.23,0.0,1,Individual,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,0,Cash,0,10.0,366.0,60,126.0,22.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,5000,5000,5000.0,17.97,180.69,D,D1,MORTGAGE,59280.0,Source Verified,Current,0,debt_consolidation,MI,10.51,0.0,0.0,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,180.69,0.0,1,Individual,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,14.0,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,0,Cash,0,6.0,80.0,36,126.0,22.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4000,4000,4000.0,18.94,146.51,D,D2,MORTGAGE,92000.0,Source Verified,Current,0,debt_consolidation,WA,16.74,0.0,0.0,10.0,0.0,5468,78.1,13.0,w,3831.93,3831.93,286.71,286.71,168.07,118.64,0.0,0.0,0.0,146.51,0.0,1,Individual,0.0,686.0,305049.0,1.0,5.0,3.0,5.0,5.0,30683.0,68.0,0.0,0.0,3761.0,70.0,7000.0,2.0,4.0,3.0,5.0,30505.0,1239.0,75.2,0.0,0.0,62.0,154.0,64.0,5.0,3.0,64.0,5.0,0.0,1.0,2.0,1.0,2.0,7.0,2.0,3.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,385183.0,36151.0,5000.0,44984.0,0,Cash,0,10.0,142.0,36,126.0,22.0,22.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,30000,30000,30000.0,16.14,731.78,C,C4,MORTGAGE,57250.0,Not Verified,Current,0,debt_consolidation,MD,26.35,0.0,0.0,12.0,0.0,829,3.6,26.0,w,29339.02,29339.02,1423.21,1423.21,660.98,762.23,0.0,0.0,0.0,731.78,0.0,1,Individual,0.0,0.0,116007.0,3.0,5.0,3.0,5.0,4.0,28845.0,89.0,2.0,4.0,516.0,54.0,23100.0,1.0,0.0,0.0,9.0,9667.0,8471.0,8.9,0.0,0.0,53.0,216.0,2.0,2.0,2.0,2.0,13.0,0.0,2.0,2.0,3.0,8.0,9.0,6.0,15.0,2.0,12.0,0.0,0.0,0.0,5.0,92.3,0.0,0.0,0.0,157548.0,29674.0,9300.0,32332.0,0,Cash,0,10.0,204.0,60,126.0,22.0,22.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [124]:
loan_data = loan_data.drop(["loan_status"], axis=1)

# PD Model

Lets start by creating the dependent variable.
We discussed the good\bad loan and default\non-default definitions.

In [ ]:
# Check values in loan_status column
loan_data['loan_status'].unique()

In [ ]:
# Chek distribution of values in loan_status column
loan_data['loan_status'].value_counts()

## Which values fit into our definition default?

The following should be treated as a default \ bad loan \ 0

Charged Off
Default
Late (31-120 days)
Does not meet the credit policy. Status:Charged Off

In [ ]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                       'Does not meet the credit policy. Status:Charged Off',
                                                       'Late (31-120 days)']), 0, 1)

## Seperate the dependent and independent variables

In [ ]:
loan_data_inputs=loan_data.drop('good_bad', axis = 1)
loan_data_targets=loan_data['good_bad']

# Computing weigh of evidence and information gain (data preparation)

In [ ]:
# Copy data into 2 new dataframes
df_inputs_prepr = loan_data_inputs
df_targets_prepr = loan_data_targets

In [ ]:
# We are going to compute weight of evidence and info for "grade" feature
df_inputs_prepr['grade'].unique()

In [ ]:
#create a new dataframe containing "grade" and traget column
df1 = pd.concat([df_inputs_prepr['grade'], df_targets_prepr], axis = 1)
df1.head(5)

In [ ]:
# Groups the data according to a criterion contained in one column.
# Does not turn the names of the values of the criterion as indexes.
# Aggregates the data in another column, using a selected function.
# In this specific case, we group by the column with index 0 and we aggregate the values of the column with index 1.
# More specifically, we count them.
# In other words, we count the values in the column with index 1 for each value of the column with index 0.
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count()

In [ ]:
# Groups the data according to a criterion contained in one column.
# Does not turn the names of the values of the criterion as indexes.
# Aggregates the data in another column, using a selected function.
# Here we calculate the mean of the values in the column with index 1 for each value of the column with index 0.

df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()

In [ ]:
# Put mean and count into the same dataframe
df1 = pd.concat([df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count(),
                df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()], axis = 1)

In [ ]:
df1

In [ ]:
# use iloc and fancy indexing to select only required columns

df1 = df1.iloc[:, [0, 1, 3]]
df1

In [ ]:
# Changes the names of the columns of a dataframe.
df1.columns = [df1.columns.values[0], 'n_obs', 'prop_good']
df1

In [ ]:
# Compute proportion of total samples

df1['prop_n_obs'] = df1['n_obs'] / df1['n_obs'].sum()
df1

In [ ]:
# compute the number of good and bad saamples for each grade

df1['n_good'] = df1['prop_good'] * df1['n_obs']
df1['n_bad'] = (1 - df1['prop_good']) * df1['n_obs']
df1

In [ ]:
# Sanity check
(57431.0 + 2328.0) == 59759
# A better sanity check

df1['n_obs'] == df1['n_good'] + df1['n_bad']

In [ ]:
# Compute proportion of good and bad loans 
df1['prop_n_good'] = df1['n_good'] / df1['n_good'].sum()
df1['prop_n_bad'] = df1['n_bad'] / df1['n_bad'].sum()
df1

In [ ]:
# Compute Woe = ln (%good/%bad)

df1['WoE'] = np.log(df1['prop_n_good'] / df1['prop_n_bad'])

In [ ]:
df1

In [ ]:
# Compute information value
df1['IV'] = (df1['prop_n_good'] - df1['prop_n_bad']) * df1['WoE']
df1['IV'] = df1['IV'].sum()
# We sum all values of a given column.
df1

In [ ]:
# WoE function for discrete unordered variables
# Here we combine all of the operations above in a function.
# The function takes 3 arguments: a dataframe, a string, and a dataframe. The function returns a dataframe as a result.

def woe_discrete(df, discrete_variabe_name, good_bad_variable_df):
    df = pd.concat([df[discrete_variabe_name], good_bad_variable_df], axis = 1)
    df = pd.concat([df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].count(),
                    df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].mean()], axis = 1)
    df = df.iloc[:, [0, 1, 3]]
    df.columns = [df.columns.values[0], 'n_obs', 'prop_good']
    df['prop_n_obs'] = df['n_obs'] / df['n_obs'].sum()
    df['n_good'] = df['prop_good'] * df['n_obs']
    df['n_bad'] = (1 - df['prop_good']) * df['n_obs']
    df['prop_n_good'] = df['n_good'] / df['n_good'].sum()
    df['prop_n_bad'] = df['n_bad'] / df['n_bad'].sum()
    df['WoE'] = np.log(df['prop_n_good'] / df['prop_n_bad'])
    #df = df.sort_values(['WoE'])
    #df = df.reset_index(drop = True)
    #df['diff_prop_good'] = df['prop_good'].diff().abs()
    #df['diff_WoE'] = df['WoE'].diff().abs()
    df['IV'] = (df['prop_n_good'] - df['prop_n_bad']) * df['WoE']
    df['IV'] = df['IV'].sum()
    return df

In [ ]:
# Check

df_temp = woe_discrete(df_inputs_prepr, 'grade', df_targets_prepr)

In [ ]:
df_temp

In [ ]:
# Check - compare results of df_temp with df1 to ensure function does not have bugs
df1

## Processing discrete features and plotting the results

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set() # Sets default style of the graphs to the seaborn style.

In [ ]:
# Below we define a function that takes 2 arguments: a dataframe and a number.
# The number parameter has a default value of 0.
# This means that if we call the function and omit the number parameter, it will be executed with it having a value of 0.
# The function displays a graph.
def plot_by_woe(df_WoE, rotation_of_x_axis_labels = 0):
    x = np.array(df_WoE.iloc[:, 0].apply(str))
    # Turns the values of the column with index 0 to strings, makes an array from these strings, and passes it to variable x.
    y = df_WoE['WoE']
    # Selects a column with label 'WoE' and passes it to variable y.
    plt.figure(figsize=(18, 6))
    # Sets the graph size to width 18 x height 6.
    plt.plot(x, y, marker = 'o', linestyle = '--', color = 'b')
    # Plots the datapoints with coordiantes variable x on the x-axis and variable y on the y-axis.
    # Sets the marker for each datapoint to a circle, the style line between the points to dashed, and the color to black.
    plt.xlabel(df_WoE.columns[0])
    # Names the x-axis with the name of the column with index 0.
    plt.ylabel('Weight of Evidence')
    # Names the y-axis 'Weight of Evidence'.
    plt.title(str('Weight of Evidence by ' + df_WoE.columns[0]))
    # Names the grapth 'Weight of Evidence by ' the name of the column with index 0.
    plt.xticks(rotation = rotation_of_x_axis_labels)
    # Rotates the labels of the x-axis a predefined number of degrees.

In [ ]:
# Test the function 
plot_by_woe(df_temp)

## Process another variable "home_ownership"  and create dummy variables

In [ ]:
# run woe_discrete function on home_ownership feature

df_temp = woe_discrete(df_inputs_prepr, 'home_ownership', df_targets_prepr)

df_temp

In [ ]:
# Plot the graph
plot_by_woe(df_temp)

There are many categories with very few observations and many categories with very different "good" %.

Therefore, we create a new discrete variable where we combine some of the categories.

'OTHERS' and 'NONE' are riskiest but are very few. 'RENT' is the next riskiest.

'ANY' are least risky but have very few observations. Conceptually, they belong to the same category. Also, their inclusion would not change anything.

We ca combine them in one category, 'RENT_OTHER_NONE_ANY'.

We end up with 3 categories: 'RENT_OTHER_NONE_ANY', 'OWN', 'MORTGAGE'.

This is somewhat arbitrary and one can create a different grouping too.

In [ ]:
df_inputs_prepr['home_ownership:RENT_OTHER_NONE_ANY'] = sum([df_inputs_prepr['home_ownership:RENT'], df_inputs_prepr['home_ownership:OTHER'],
                                                      df_inputs_prepr['home_ownership:NONE'],df_inputs_prepr['home_ownership:ANY']])

'RENT_OTHER_NONE_ANY' is called a  reference category.

## Processing another discrete variable addr_state which has many values

In [ ]:
# 'addr_state'
df_inputs_prepr['addr_state'].unique()

In [ ]:
# Compute  weight of evidence.
df_temp = woe_discrete(df_inputs_prepr, 'addr_state', df_targets_prepr)

In [ ]:
#Sort data by WoE
df_temp.sort_values(by=['WoE'], inplace= True)

In [ ]:
df_temp

In [ ]:
# Plot WoE
plot_by_woe(df_temp)

In [ ]:
print (df_temp.shape)

In [ ]:
# if ['addr_state:ND'] in df_inputs_prepr.columns.values:
#     pass
# else:
#     df_inputs_prepr['addr_state:ND'] = 0

The top 2 states (NE and IA) have 13 samples and bottom 2 states (ME and ID) also have very few samples.
We can club them into a category

In [ ]:
# Plot exclusing first 2 and last 3 states
plot_by_woe(df_temp.iloc[2: -2, : ])

In [ ]:
#Plot exclusing first 5 and last 5 values
plot_by_woe(df_temp.iloc[6: -6, : ])

 We create the following categories:
 
 'ND' 'NE' 'IA' NV' 'FL' 'HI' 'AL' # States with least information and therfore highest risk in a single cateory
 
 'NM' 'VA'
 
 'NY' # High number of samples (borrowers)
 
 'OK' 'TN' 'MO' 'LA' 'MD' 'NC'
 
 'CA' # High number of samples (borrowers)
 
 'UT' 'KY' 'AZ' 'NJ' # Similar WoE also have similar number of observations (borrowers)
 
 'AR' 'MI' 'PA' 'OH' 'MN' # Similar WoE also have similar number of observations (borrowers)
 
 'RI' 'MA' 'DE' 'SD' 'IN' # Similar WoE also have similar number of observations (borrowers)
 
 'GA' 'WA' 'OR' # Similar WoE also have similar number of observations (borrowers)
 
 'WI' 'MT' # Similar WoE but a bit apart in number of observations (borrowers)
 
 'TX' # Large number of observation
 
 'IL' 'CT' ## Similar WoE and number of observations are similar
 
 'KS' 'SC' 'CO' 'VT' 'AK' 'MS' # Similar WoE and number of observations are similar
 
 'WV' 'NH' 'WY' 'DC' 'ME' 'ID' # States with low number of observations and therefore they are clubbed together

 'IA_NV_HI_ID_AL_FL' will be the reference category. This is the category with lowest weight of evidence

In [ ]:
df_inputs_prepr['addr_state:ND_NE_IA_NV_FL_HI_AL'] = sum([df_inputs_prepr['addr_state:ND'], df_inputs_prepr['addr_state:NE'],
                                              df_inputs_prepr['addr_state:IA'], df_inputs_prepr['addr_state:NV'],
                                              df_inputs_prepr['addr_state:FL'], df_inputs_prepr['addr_state:HI'],
                                                          df_inputs_prepr['addr_state:AL']])

df_inputs_prepr['addr_state:NM_VA'] = sum([df_inputs_prepr['addr_state:NM'], df_inputs_prepr['addr_state:VA']])

df_inputs_prepr['addr_state:OK_TN_MO_LA_MD_NC'] = sum([df_inputs_prepr['addr_state:OK'], df_inputs_prepr['addr_state:TN'],
                                              df_inputs_prepr['addr_state:MO'], df_inputs_prepr['addr_state:LA'],
                                              df_inputs_prepr['addr_state:MD'], df_inputs_prepr['addr_state:NC']])

df_inputs_prepr['addr_state:UT_KY_AZ_NJ'] = sum([df_inputs_prepr['addr_state:UT'], df_inputs_prepr['addr_state:KY'],
                                              df_inputs_prepr['addr_state:AZ'], df_inputs_prepr['addr_state:NJ']])

df_inputs_prepr['addr_state:AR_MI_PA_OH_MN'] = sum([df_inputs_prepr['addr_state:AR'], df_inputs_prepr['addr_state:MI'],
                                              df_inputs_prepr['addr_state:PA'], df_inputs_prepr['addr_state:OH'],
                                              df_inputs_prepr['addr_state:MN']])

df_inputs_prepr['addr_state:RI_MA_DE_SD_IN'] = sum([df_inputs_prepr['addr_state:RI'], df_inputs_prepr['addr_state:MA'],
                                              df_inputs_prepr['addr_state:DE'], df_inputs_prepr['addr_state:SD'],
                                              df_inputs_prepr['addr_state:IN']])

df_inputs_prepr['addr_state:GA_WA_OR'] = sum([df_inputs_prepr['addr_state:GA'], df_inputs_prepr['addr_state:WA'],
                                              df_inputs_prepr['addr_state:OR']])

df_inputs_prepr['addr_state:WI_MT'] = sum([df_inputs_prepr['addr_state:WI'], df_inputs_prepr['addr_state:MT']])

df_inputs_prepr['addr_state:IL_CT'] = sum([df_inputs_prepr['addr_state:IL'], df_inputs_prepr['addr_state:CT']])

df_inputs_prepr['addr_state:KS_SC_CO_VT_AK_MS'] = sum([df_inputs_prepr['addr_state:KS'], df_inputs_prepr['addr_state:SC'],
                                              df_inputs_prepr['addr_state:CO'], df_inputs_prepr['addr_state:VT'],
                                              df_inputs_prepr['addr_state:AK'], df_inputs_prepr['addr_state:MS']])

df_inputs_prepr['addr_state:WV_NH_WY_DC_ME_ID'] = sum([df_inputs_prepr['addr_state:WV'], df_inputs_prepr['addr_state:NH'],
                                              df_inputs_prepr['addr_state:WY'], df_inputs_prepr['addr_state:DC'],
                                              df_inputs_prepr['addr_state:ME'], df_inputs_prepr['addr_state:ID']])

In [ ]:
# 'verification_status'
df_temp = woe_discrete(df_inputs_prepr, 'verification_status', df_targets_prepr)
# We calculate weight of evidence.
df_temp

In [ ]:
# plot WoE
plot_by_woe(df_temp)

There is nothing to do here

In [ ]:
# 'purpose'
df_temp = woe_discrete(df_inputs_prepr, 'purpose', df_targets_prepr)
# We calculate weight of evidence.
df_temp

In [ ]:
# plot WoE
df_temp.sort_values(by=['WoE'], inplace=True)
plot_by_woe(df_temp,90)

 We combine 'educational', 'small_business', 'wedding', 'renewable_energy', 'moving', 'house' in one category: 'educ__sm_b__wedd__ren_en__mov__house'.
 
 We combine 'other', 'medical', 'vacation' in one category: 'oth__med__vacation'.
 
We combine 'major_purchase', 'car', 'home_improvement' in one category: 'major_purch__car__home_impr'.

We leave 'debt_consolidtion' in a separate category.

We leave 'credit_card' in a separate category.


'educ__sm_b__wedd__ren_en__mov__house' will be the reference category.

In [ ]:
df_inputs_prepr['purpose:educ__sm_b__wedd__ren_en__mov__house'] = sum([df_inputs_prepr['purpose:educational'], df_inputs_prepr['purpose:small_business'],
                                                                 df_inputs_prepr['purpose:wedding'], df_inputs_prepr['purpose:renewable_energy'],
                                                                 df_inputs_prepr['purpose:moving'], df_inputs_prepr['purpose:house']])
df_inputs_prepr['purpose:oth__med__vacation'] = sum([df_inputs_prepr['purpose:other'], df_inputs_prepr['purpose:medical'],
                                             df_inputs_prepr['purpose:vacation']])
df_inputs_prepr['purpose:major_purch__car__home_impr'] = sum([df_inputs_prepr['purpose:major_purchase'], df_inputs_prepr['purpose:car'],
                                                        df_inputs_prepr['purpose:home_improvement']])

In [ ]:
# 'initial_list_status'
df_temp = woe_discrete(df_inputs_prepr, 'initial_list_status', df_targets_prepr)
df_temp

In [ ]:
# plot WoE
plot_by_woe(df_temp)

Nothing to do for "initial_list_status" either

# Handling continuous features

By law, most countries require use of easy to interpret PD model

Because of this, just like we used dummy variables for home (own/rent/mortgage) we will use dummy variable for 

continous features as well

We will divide a contionous feature such as income into bins (categories) and then apply the same process as we did 

before for discrete variables

One different is that with continous variables the order has meaning. 

For example, for contionous variable like income, if we create bins such as 0-10, 10-20, 30-40 and so on. 

The group 50-60 represents a lower income group whereas the group 90-100 presents a higher income group.

Compare this with a discrete variable such as purpose_of_loan. A education loan and a car loan have different purposes 

but they done represent any ordering. 


Note: Read nominal vs ordinal from basic statistics for futher clarification

In [ ]:
# WoE function for ordered discrete and continuous variables
# Same function as before difference: we order the results by the values of a different column.
# The function takes 3 arguments: a dataframe, a string, and a dataframe. The function returns a dataframe as a result.
def woe_ordered_continuous(df, discrete_variabe_name, good_bad_variable_df):
    df = pd.concat([df[discrete_variabe_name], good_bad_variable_df], axis = 1)
    df = pd.concat([df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].count(),
                    df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].mean()], axis = 1)
    df = df.iloc[:, [0, 1, 3]]
    df.columns = [df.columns.values[0], 'n_obs', 'prop_good']
    df['prop_n_obs'] = df['n_obs'] / df['n_obs'].sum()
    df['n_good'] = df['prop_good'] * df['n_obs']
    df['n_bad'] = (1 - df['prop_good']) * df['n_obs']
    df['prop_n_good'] = df['n_good'] / df['n_good'].sum()
    df['prop_n_bad'] = df['n_bad'] / df['n_bad'].sum()
    df['WoE'] = np.log(df['prop_n_good'] / df['prop_n_bad'])
    #df = df.sort_values(['WoE']) # commented out because we want to preserve natural ordering
    #df = df.reset_index(drop = True) # not neededss
    df['diff_prop_good'] = df['prop_good'].diff().abs()
    df['diff_WoE'] = df['WoE'].diff().abs()
    df['IV'] = (df['prop_n_good'] - df['prop_n_bad']) * df['WoE']
    df['IV'] = df['IV'].sum()
    return df

## Creating dummy variables for continous features - term_int and emp_length_int


Note: term_int and emp_length_int are ordered discrete variables that are assumed to be contionous and have very few distinct values

In [ ]:
# Check the values in term_int
df_inputs_prepr['term_int'].unique()

In [ ]:
# Compute WoE using woe_ordered_continuous function

df_temp = woe_ordered_continuous(df_inputs_prepr, 'term_int', df_targets_prepr)
df_temp

In [ ]:
#Check plot
plot_by_woe(df_temp)

Create dummy categories but we dont have to create different bins here
term:60 will be the reference category

In [ ]:
df_inputs_prepr['term:36'] = np.where((df_inputs_prepr['term_int'] == 36), 1, 0)
df_inputs_prepr['term:60'] = np.where((df_inputs_prepr['term_int'] == 60), 1, 0)

In [ ]:
# emp_length_int
df_inputs_prepr['emp_length_int'].unique()

In [ ]:
# Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr, 'emp_length_int', df_targets_prepr)
df_temp

In [ ]:
# Plot WoE
plot_by_woe(df_temp)

We create the following cateories for emp_length_int

emp_length:0 - lowest Woe. This will also be the reference category

emp_length:1 

emp_length:2-4 - Simiar WoE and similar number of observations

emp_length:5-6 - Simiar WoE and similar number of observations

emp_length:7-9 - Simiar WoE and similar number of observations. One can also create 3 different categories here but fewer dummy variables are preferred. This is a judgement call.

emp_length:10 - High WoE

In [ ]:
# Create categories 
# 'emp_length:0' will be the reference category
df_inputs_prepr['emp_length:0'] = np.where(df_inputs_prepr['emp_length_int'].isin([0]), 1, 0)
df_inputs_prepr['emp_length:1'] = np.where(df_inputs_prepr['emp_length_int'].isin([1]), 1, 0)
df_inputs_prepr['emp_length:2-4'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(2, 5)), 1, 0)
df_inputs_prepr['emp_length:5-6'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(5, 7)), 1, 0)
df_inputs_prepr['emp_length:7-9'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(7, 10)), 1, 0)
df_inputs_prepr['emp_length:10'] = np.where(df_inputs_prepr['emp_length_int'].isin([10]), 1, 0)

## Creating dummy variables for continous features  (advanced)

Strategy:

1. Use Fine classing to create categories based on values

2. Use coarse classing to combine some of the categories created using fine classing if required


## Applying the above strategy to mths_since_issue_d

In [ ]:
df_inputs_prepr['mths_since_issue_d'].unique()

In [ ]:
# Fine classing step using pd.cut to divide into 50 categories

df_inputs_prepr['mths_since_issue_d_factor'] = pd.cut(df_inputs_prepr['mths_since_issue_d'], 50)

In [ ]:
df_inputs_prepr['mths_since_issue_d_factor']

As seen above each sample as been assigned to category.

Lets get a list of all unique categories

(43.2, 45.0] - refers to a value between 43.2 (inclusive) and 45 ( not included).

In order words, 43.2 <= value < 45

In [ ]:
# Compute woe using the previous created function
df_temp = woe_ordered_continuous(df_inputs_prepr, 'mths_since_issue_d_factor', df_targets_prepr)
df_temp

In [ ]:
#Plot weight by evidence. The second parameter rotates the xlabel by 90 degrees
plot_by_woe(df_temp,90)

The first 3 values should have their own categorie because the WoE is quite different for each of them
We will create a seperate dummy variable for each of the following categories

1. <38
2. 38-39
3. 40-41

In [ ]:
# Exlcude first 3 categories and look at others
plot_by_woe(df_temp.iloc[3: , : ], 90)


We create the following categories based on above graph

42 - 48 - Their WoE and number of samples is similar

49 - 52 - Their WoE and number of samples is similar

53 - 64 - Their WoE and number of samples is similar

65 - 84 - number of samples is similar

< 84 - number of samples is similar

In [ ]:
# New categories: Coarse classing step
# < 38, 38 - 39, 40 - 41, 42 - 48, 49 - 52, 53 - 64, 65 - 84, > 84.
df_inputs_prepr['mths_since_issue_d:<38'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38)), 1, 0)
df_inputs_prepr['mths_since_issue_d:38-39'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38, 40)), 1, 0)
df_inputs_prepr['mths_since_issue_d:40-41'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(40, 42)), 1, 0)
df_inputs_prepr['mths_since_issue_d:42-48'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(42, 49)), 1, 0)
df_inputs_prepr['mths_since_issue_d:49-52'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(49, 53)), 1, 0)
df_inputs_prepr['mths_since_issue_d:53-64'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(53, 65)), 1, 0)
df_inputs_prepr['mths_since_issue_d:65-84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(65, 85)), 1, 0)
df_inputs_prepr['mths_since_issue_d:>84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(85, int(df_inputs_prepr['mths_since_issue_d'].max()))), 1, 0)

# Applying the same strategy to int_rate feature

In [ ]:
# Fine classing  using pd.cut to put into 50 categories
df_inputs_prepr['int_rate_factor'] = pd.cut(df_inputs_prepr['int_rate'], 50)

In [ ]:
# compute the WoE
df_temp = woe_ordered_continuous(df_inputs_prepr, 'int_rate_factor', df_targets_prepr)

In [ ]:
df_temp

In [ ]:
#plot with rotation
plot_by_woe(df_temp, 90)

There seems to a continous down trend overall in this field so coarse grouping should be easier

The first 9 points have WoE is up and down. Therefore, we look at the number of samples.

Since the number of samples is similar we group them together in a category named "< 9.548"

Categories


"< 9.548" - WoE varies but similar number of samples

"9.548 - 12.025" - WoE is range bound 

"12.025 - 15.74" - WoE is range bound

"15.74 - 20.281" - WoE is range bound

"> 20.281" - WoE is range bound and few samples in each category

In [ ]:
df_inputs_prepr['int_rate:<9.548'] = np.where((df_inputs_prepr['int_rate'] <= 9.548), 1, 0)
df_inputs_prepr['int_rate:9.548-12.025'] = np.where((df_inputs_prepr['int_rate'] > 9.548) & (df_inputs_prepr['int_rate'] <= 12.025), 1, 0)
df_inputs_prepr['int_rate:12.025-15.74'] = np.where((df_inputs_prepr['int_rate'] > 12.025) & (df_inputs_prepr['int_rate'] <= 15.74), 1, 0)
df_inputs_prepr['int_rate:15.74-20.281'] = np.where((df_inputs_prepr['int_rate'] > 15.74) & (df_inputs_prepr['int_rate'] <= 20.281), 1, 0)
df_inputs_prepr['int_rate:>20.281'] = np.where((df_inputs_prepr['int_rate'] > 20.281), 1, 0)

## mths_since_earliest_cr_line

In [ ]:
# fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_inputs_prepr['mths_since_earliest_cr_line_factor'] = pd.cut(df_inputs_prepr['mths_since_earliest_cr_line'], 50)
#Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr, 'mths_since_earliest_cr_line_factor', df_targets_prepr)
df_temp

In [ ]:
#Plot WoE
plot_by_woe(df_temp, 90)

In [ ]:
#Plot WoE leaving first 5 samples
plot_by_woe(df_temp.iloc[6: , : ], 90)

Following categories are created

1. "< 140"

2. 141 - 164

3. 165 - 247

4. 248 - 270 

5. 271 - 352

6.  "> 352"

In [ ]:
# Coarse binning step
df_inputs_prepr['mths_since_earliest_cr_line:<140'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:141-164'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140, 165)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:165-247'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(165, 248)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:248-270'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(248, 271)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:271-352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(271, 353)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:>352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(353, int(df_inputs_prepr['mths_since_earliest_cr_line'].max()))), 1, 0)

## delinq_2yrs

In [ ]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'delinq_2yrs', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp)

Categories created:

1.  0

2. 1-3

3. ">= 4"

In [ ]:
#create categories
df_inputs_prepr['delinq_2yrs:0'] = np.where((df_inputs_prepr['delinq_2yrs'] == 0), 1, 0)
df_inputs_prepr['delinq_2yrs:1-3'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 1) & (df_inputs_prepr['delinq_2yrs'] <= 3), 1, 0)
df_inputs_prepr['delinq_2yrs:>=4'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 9), 1, 0)

## inq_last_6mths

In [ ]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'inq_last_6mths', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp)

Categories identified

1. 0

2. 1 - 2

3. 3 - 6 

4. "> 6"

In [ ]:
df_inputs_prepr['inq_last_6mths:0'] = np.where((df_inputs_prepr['inq_last_6mths'] == 0), 1, 0)
df_inputs_prepr['inq_last_6mths:1-2'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 1) & (df_inputs_prepr['inq_last_6mths'] <= 2), 1, 0)
df_inputs_prepr['inq_last_6mths:3-6'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 3) & (df_inputs_prepr['inq_last_6mths'] <= 6), 1, 0)
df_inputs_prepr['inq_last_6mths:>6'] = np.where((df_inputs_prepr['inq_last_6mths'] > 6), 1, 0)

## open_acc

In [ ]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'open_acc', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp, 90)

In [ ]:
plot_by_woe(df_temp.iloc[ : 40, :], 90)

Categories identified

1. 0
2. 1-3
3. 4-12
4. 13-17
5. 18-22
6. 23-25
7. 26-30
8. '>30'

In [ ]:
# create categories
df_inputs_prepr['open_acc:0'] = np.where((df_inputs_prepr['open_acc'] == 0), 1, 0)
df_inputs_prepr['open_acc:1-3'] = np.where((df_inputs_prepr['open_acc'] >= 1) & (df_inputs_prepr['open_acc'] <= 3), 1, 0)
df_inputs_prepr['open_acc:4-12'] = np.where((df_inputs_prepr['open_acc'] >= 4) & (df_inputs_prepr['open_acc'] <= 12), 1, 0)
df_inputs_prepr['open_acc:13-17'] = np.where((df_inputs_prepr['open_acc'] >= 13) & (df_inputs_prepr['open_acc'] <= 17), 1, 0)
df_inputs_prepr['open_acc:18-22'] = np.where((df_inputs_prepr['open_acc'] >= 18) & (df_inputs_prepr['open_acc'] <= 22), 1, 0)
df_inputs_prepr['open_acc:23-25'] = np.where((df_inputs_prepr['open_acc'] >= 23) & (df_inputs_prepr['open_acc'] <= 25), 1, 0)
df_inputs_prepr['open_acc:26-30'] = np.where((df_inputs_prepr['open_acc'] >= 26) & (df_inputs_prepr['open_acc'] <= 30), 1, 0)
df_inputs_prepr['open_acc:>=31'] = np.where((df_inputs_prepr['open_acc'] >= 31), 1, 0)

# pub_rec

In [ ]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'pub_rec', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp, 90)

Categories indentified

1. 0-2

2. 3-4

3. ">=5"

In [ ]:
#create categories

df_inputs_prepr['pub_rec:0-2'] = np.where((df_inputs_prepr['pub_rec'] >= 0) & (df_inputs_prepr['pub_rec'] <= 2), 1, 0)
df_inputs_prepr['pub_rec:3-4'] = np.where((df_inputs_prepr['pub_rec'] >= 3) & (df_inputs_prepr['pub_rec'] <= 4), 1, 0)
df_inputs_prepr['pub_rec:>=5'] = np.where((df_inputs_prepr['pub_rec'] >= 5), 1, 0)

## total_acc

In [ ]:
df_inputs_prepr['total_acc_factor'] = pd.cut(df_inputs_prepr['total_acc'], 50)
df_temp = woe_ordered_continuous(df_inputs_prepr, 'total_acc_factor', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp, 90)

Categories identified

1. <=27'
2. '28-51'
3. '>51'

In [ ]:
df_inputs_prepr['total_acc:<=27'] = np.where((df_inputs_prepr['total_acc'] <= 27), 1, 0)
df_inputs_prepr['total_acc:28-51'] = np.where((df_inputs_prepr['total_acc'] >= 28) & (df_inputs_prepr['total_acc'] <= 51), 1, 0)
df_inputs_prepr['total_acc:>=52'] = np.where((df_inputs_prepr['total_acc'] >= 52), 1, 0)

## acc_now_delinq

In [ ]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'acc_now_delinq', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp)

Categories identified

1. 0

2. ">=1"

In [ ]:
df_inputs_prepr['acc_now_delinq:0'] = np.where((df_inputs_prepr['acc_now_delinq'] == 0), 1, 0)
df_inputs_prepr['acc_now_delinq:>=1'] = np.where((df_inputs_prepr['acc_now_delinq'] >= 1), 1, 0)

## # total_rev_hi_lim

In [ ]:
df_inputs_prepr['total_rev_hi_lim_factor'] = pd.cut(df_inputs_prepr['total_rev_hi_lim'], 2000)
df_temp = woe_ordered_continuous(df_inputs_prepr, 'total_rev_hi_lim_factor', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp.iloc[: 50, : ], 90)

Categories identified

1.  '<=5K'

2.   '5K-10K'

3. '10K-20K'

4. '20K-30K'

5. '30K-40K'

6. '40K-55K'

7. '55K-95K'

8. '>95K'

In [ ]:
df_inputs_prepr['total_rev_hi_lim:<=5K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] <= 5000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:5K-10K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 5000) & (df_inputs_prepr['total_rev_hi_lim'] <= 10000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:10K-20K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 10000) & (df_inputs_prepr['total_rev_hi_lim'] <= 20000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:20K-30K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 20000) & (df_inputs_prepr['total_rev_hi_lim'] <= 30000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:30K-40K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 30000) & (df_inputs_prepr['total_rev_hi_lim'] <= 40000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:40K-55K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 40000) & (df_inputs_prepr['total_rev_hi_lim'] <= 55000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:55K-95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 55000) & (df_inputs_prepr['total_rev_hi_lim'] <= 95000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:>95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 95000), 1, 0)

# Handling continous features - annual_inc & mths_since_last_delinq


Some features like annual_inc might have high variance. Such variables require some special handling

In [ ]:
# Create a feature named "annual_inc_factor" using pd.cut (Fine classing)

df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 50)

# Compute WoE

df_temp = woe_ordered_continuous(df_inputs_prepr, 'annual_inc_factor', df_targets_prepr)


df_temp

The problem with this categorisation is that the first interval (category) contains 351904 samples which is 94.33% of the total samples. 50 categories dont seem to be enough. 
So we need more classes. We can try with 100 This is somewhat arbitrary

In [ ]:
# Create a feature named "annual_inc_factor" using pd.cut (Fine classing)

df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 100)

# Compute WoE

df_temp = woe_ordered_continuous(df_inputs_prepr, 'annual_inc_factor', df_targets_prepr)


df_temp

The problem is somewhat alleviated but still persists. The firt category now contains 231445 samples which is 62% of the total samples.

This distribution makes sense for annual_inc because sameples with high annual income would be less than the number of samples with low annual income.

One strategy could be treat high income and low income as two seperate categories

Lets create a category having annual income greater than 140K

In [ ]:
# Collecting all samples with annual_inc <=140k into a dataframe

df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['annual_inc'] <= 140000, : ]

In [ ]:
# Fine classing using just the samples having annual_inc <= 140K

df_inputs_prepr_temp["annual_inc_factor"] = pd.cut(df_inputs_prepr_temp['annual_inc'], 50)

# Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'annual_inc_factor', df_targets_prepr[df_inputs_prepr_temp.index])


df_temp

In [ ]:
plot_by_woe(df_temp, 90)

WoE is monotonically decreasing with income, so we split income in 10 equal categories, each with width of 15k.

All samples with more than 140K annual_inc will be in one category.

All samples with less than 20K annual inc will be in one category.

In [ ]:
#Creating categories

df_inputs_prepr['annual_inc:<20K'] = np.where((df_inputs_prepr['annual_inc'] <= 20000), 1, 0)
df_inputs_prepr['annual_inc:20K-30K'] = np.where((df_inputs_prepr['annual_inc'] > 20000) & (df_inputs_prepr['annual_inc'] <= 30000), 1, 0)
df_inputs_prepr['annual_inc:30K-40K'] = np.where((df_inputs_prepr['annual_inc'] > 30000) & (df_inputs_prepr['annual_inc'] <= 40000), 1, 0)
df_inputs_prepr['annual_inc:40K-50K'] = np.where((df_inputs_prepr['annual_inc'] > 40000) & (df_inputs_prepr['annual_inc'] <= 50000), 1, 0)
df_inputs_prepr['annual_inc:50K-60K'] = np.where((df_inputs_prepr['annual_inc'] > 50000) & (df_inputs_prepr['annual_inc'] <= 60000), 1, 0)
df_inputs_prepr['annual_inc:60K-70K'] = np.where((df_inputs_prepr['annual_inc'] > 60000) & (df_inputs_prepr['annual_inc'] <= 70000), 1, 0)
df_inputs_prepr['annual_inc:70K-80K'] = np.where((df_inputs_prepr['annual_inc'] > 70000) & (df_inputs_prepr['annual_inc'] <= 80000), 1, 0)
df_inputs_prepr['annual_inc:80K-90K'] = np.where((df_inputs_prepr['annual_inc'] > 80000) & (df_inputs_prepr['annual_inc'] <= 90000), 1, 0)
df_inputs_prepr['annual_inc:90K-100K'] = np.where((df_inputs_prepr['annual_inc'] > 90000) & (df_inputs_prepr['annual_inc'] <= 100000), 1, 0)
df_inputs_prepr['annual_inc:100K-120K'] = np.where((df_inputs_prepr['annual_inc'] > 100000) & (df_inputs_prepr['annual_inc'] <= 120000), 1, 0)
df_inputs_prepr['annual_inc:120K-140K'] = np.where((df_inputs_prepr['annual_inc'] > 120000) & (df_inputs_prepr['annual_inc'] <= 140000), 1, 0)
df_inputs_prepr['annual_inc:>140K'] = np.where((df_inputs_prepr['annual_inc'] > 140000), 1, 0)

## mths_since_last_delinq

In [ ]:
# This feature has a lot of nulls
df_inputs_prepr['mths_since_last_delinq'].isnull().count()

One strategy to deal with these missing values is to create a dummy variable that is set 1 when value is missing and 0 when value is not missing

For samples not having nulls we do the usual

In [ ]:
#Fine classing samples which are not missing

df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_delinq'])]


df_inputs_prepr_temp['mths_since_last_delinq_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_delinq'], 50)


df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'mths_since_last_delinq_factor', df_targets_prepr[df_inputs_prepr_temp.index])

In [ ]:
df_temp

In [ ]:
# Plot WoE
plot_by_woe(df_temp, 90)

Create the following categories

1. Missing

2. 0-3

3. 4-30

4. 31-56

5. ">=57"

In [ ]:
# Create the categories
df_inputs_prepr['mths_since_last_delinq:Missing'] = np.where((df_inputs_prepr['mths_since_last_delinq'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_delinq:0-3'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 0) & (df_inputs_prepr['mths_since_last_delinq'] <= 3), 1, 0)
df_inputs_prepr['mths_since_last_delinq:4-30'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 4) & (df_inputs_prepr['mths_since_last_delinq'] <= 30), 1, 0)
df_inputs_prepr['mths_since_last_delinq:31-56'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 31) & (df_inputs_prepr['mths_since_last_delinq'] <= 56), 1, 0)
df_inputs_prepr['mths_since_last_delinq:>=57'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 57), 1, 0)

# DIY 4 

Examine weight of evidence and determine the categories that should be created as dummy variables for the probability of default (PD) model for two continuous variables: 

‘dti’ (debt to income ratio)

‘mths_since_last_record’

For each of the two variables:

1. Determine whether you should do fine classing of the variable, that is, cut it into categories. If yes, use the ‘pd.cut’ method to do the fine classing.

2. Run the ‘woe_discrete’ function with the following arguments: the ‘df_inputs_prepr’ dataframe, the respective independent variable, and the ‘df_targets_prepr’ dataframe. Display the dataframe with results.

3. Run the ‘plot_by_woe’ function with the dataframe with results as an argument. Display the chart with weights of evidence by original categories of the independent variable.

4. Examine the chart and the dataframe with results. Decide what categories of the independent variable we should have as dummy variables for the PD model and create them, if necessary.

5. Decide which one should be the reference category and make a note for it.

# dti

In [ ]:
# Fine classing into 100 categories using pd.cut
df_inputs_prepr['dti_factor'] = pd.cut(df_inputs_prepr['dti'], 100)
#Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr, 'dti_factor', df_targets_prepr)
df_temp

In [ ]:
plot_by_woe(df_temp, 90)

Just  income, initial examination shows that most values are lower than 35.

Therefore, lets split into 2 groups one havig dti <= 35 and another having more than 35

In [ ]:
df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['dti'] <= 35, : ]

In [ ]:
# Fine classing using samples with dti <= 35
df_inputs_prepr_temp['dti_factor'] = pd.cut(df_inputs_prepr_temp['dti'], 50)
#Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'dti_factor', df_targets_prepr[df_inputs_prepr_temp.index])
df_temp

In [ ]:
plot_by_woe(df_temp, 90)

In [ ]:
# Create categories
df_inputs_prepr['dti:<=1.4'] = np.where((df_inputs_prepr['dti'] <= 1.4), 1, 0)
df_inputs_prepr['dti:1.4-3.5'] = np.where((df_inputs_prepr['dti'] > 1.4) & (df_inputs_prepr['dti'] <= 3.5), 1, 0)
df_inputs_prepr['dti:3.5-7.7'] = np.where((df_inputs_prepr['dti'] > 3.5) & (df_inputs_prepr['dti'] <= 7.7), 1, 0)
df_inputs_prepr['dti:7.7-10.5'] = np.where((df_inputs_prepr['dti'] > 7.7) & (df_inputs_prepr['dti'] <= 10.5), 1, 0)
df_inputs_prepr['dti:10.5-16.1'] = np.where((df_inputs_prepr['dti'] > 10.5) & (df_inputs_prepr['dti'] <= 16.1), 1, 0)
df_inputs_prepr['dti:16.1-20.3'] = np.where((df_inputs_prepr['dti'] > 16.1) & (df_inputs_prepr['dti'] <= 20.3), 1, 0)
df_inputs_prepr['dti:20.3-21.7'] = np.where((df_inputs_prepr['dti'] > 20.3) & (df_inputs_prepr['dti'] <= 21.7), 1, 0)
df_inputs_prepr['dti:21.7-22.4'] = np.where((df_inputs_prepr['dti'] > 21.7) & (df_inputs_prepr['dti'] <= 22.4), 1, 0)
df_inputs_prepr['dti:22.4-35'] = np.where((df_inputs_prepr['dti'] > 22.4) & (df_inputs_prepr['dti'] <= 35), 1, 0)
df_inputs_prepr['dti:>35'] = np.where((df_inputs_prepr['dti'] > 35), 1, 0)

## mths_since_last_record

In [ ]:
# Count missing values
df_inputs_prepr['mths_since_last_record'].isnull().count()

In [ ]:
# Create category having not nulls

df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_record'])]

# Fine classing using samples with not null values

df_inputs_prepr_temp['mths_since_last_record_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_record'], 50)

# Compute WoE
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'mths_since_last_record_factor', df_targets_prepr[df_inputs_prepr_temp.index])

df_temp

In [ ]:
# Plot WoE
plot_by_woe(df_temp, 90)

In [ ]:
# Create Categories

# Categories: 'Missing', '0-2', '3-20', '21-31', '32-80', '81-86', '>86'
df_inputs_prepr['mths_since_last_record:Missing'] = np.where((df_inputs_prepr['mths_since_last_record'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_record:0-2'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 0) & (df_inputs_prepr['mths_since_last_record'] <= 2), 1, 0)
df_inputs_prepr['mths_since_last_record:3-20'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 3) & (df_inputs_prepr['mths_since_last_record'] <= 20), 1, 0)
df_inputs_prepr['mths_since_last_record:21-31'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 21) & (df_inputs_prepr['mths_since_last_record'] <= 31), 1, 0)
df_inputs_prepr['mths_since_last_record:32-80'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 32) & (df_inputs_prepr['mths_since_last_record'] <= 80), 1, 0)
df_inputs_prepr['mths_since_last_record:81-86'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 81) & (df_inputs_prepr['mths_since_last_record'] <= 86), 1, 0)
df_inputs_prepr['mths_since_last_record:>86'] = np.where((df_inputs_prepr['mths_since_last_record'] > 86), 1, 0)

In [ ]:
df_inputs_prepr.head()

In [ ]:
df_inputs_prepr.shape

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# 80-20 split into train-test sets

loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(df_inputs_prepr,df_targets_prepr, test_size = 0.2, random_state = 42)

In [ ]:
#Check the size
print (loan_data_inputs_train.shape)
print (loan_data_inputs_test.shape)
print (loan_data_targets_train.shape)
print (loan_data_targets_test.shape)

In [ ]:
# Save the prepared datasets ito pickle files


print (loan_data_inputs_train.shape)
print (loan_data_targets_train.shape)

#loan_data_inputs_train.to_pickle('loan_data_inputs_train.pkl')
#loan_data_targets_train.to_pickle('loan_data_targets_train.pkl')
#loan_data_inputs_test.to_pickle('loan_data_inputs_test.pkl')
#loan_data_targets_test.to_pickle('loan_data_targets_test.pkl')

# Load data and select features

In [ ]:
loan_data_inputs_train = pd.read_pickle('loan_data_inputs_train.pkl')
loan_data_targets_train = pd.read_pickle('loan_data_targets_train.pkl')
loan_data_inputs_test = pd.read_pickle('loan_data_inputs_test.pkl')
loan_data_targets_test = pd.read_pickle('loan_data_targets_test.pkl')

In [ ]:
loan_data_inputs_train.head()

In [ ]:
loan_data_targets_train.head()

In [ ]:
loan_data_inputs_test.head()

In [ ]:
loan_data_targets_test.head()

In [ ]:
#Sanity check
print (loan_data_inputs_train.shape)
print (loan_data_targets_train.shape)
print (loan_data_inputs_test.shape)
print (loan_data_targets_test.shape)

## Feature selection

We are going to use the dummy variables that we created in the previous sessions

In [ ]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

The reference category is a basline which we will assume to be 1 when everything else is a 0. 

We will see later when we interpret the model how the reference category helps us compare the independent variables.

We will drop the reference category from the train set though

In [ ]:
# Create a list containing all reference category dummy variables

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
# From the dataframe with input variables, drop the variables with variable names in the list with reference categories. 
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)

In [ ]:
inputs_train.shape

In [ ]:
inputs_train.head()

# PD Model Fitting


We will use sklearn's logistic regression class to train our PD model

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
logreg = reg = LogisticRegression()

In [ ]:
# Display all rows in a pandas dataframe
pd.options.display.max_rows = None

In [ ]:
# Fit using training data

reg.fit(inputs_train, loan_data_targets_train)

In [ ]:
# Intercept of the model

print (logreg.intercept_)

In [ ]:
# Coefficients of the model

print (logreg.coef_)
print (logreg.coef_.shape) # Sanity check

We have 104 features and therefore 104 coefficients in the model built above.

Let us collect the intercept and coefficients (model parameters) into a seperate summary_table

In [ ]:
# Collect all feature names into a list
feature_name = inputs_train.columns.values

In [ ]:
# Creates a dataframe with a column titled 'Feature name' and row values contained in the 'feature_name' variable.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)

# Creates a new column in the dataframe, called 'Coefficients',
# with row values the transposed coefficients from the 'LogisticRegression' object.
summary_table['Coefficients'] = np.transpose(reg.coef_)

Add a index on top of summary table to make room for storing intercept.

Adding a row in pandas is not straight forward

In [ ]:
# Increases the index of every row of the dataframe with 1.
summary_table.index = summary_table.index + 1
# Store intercept in the row with index 0 of the dataframe.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Sorts the dataframe by index.
summary_table = summary_table.sort_index()
summary_table

The next step in credit risk modeling is to compute the p-value for each of the independent varibles.

Recall from statistics class a independent variable is considered statistically significant for predicting the dependent variable if the p-value of the independent variable is less than 0.05.

Note: There is no scientific reason behind picking 0.05 as threshold of p-value. It is somewhat arbitrary.

Sklearn does not have a function to compute p-values.

Therefore we will write the function to compute p-values

We will enhance the inbuilt LogisticRegression class to compute p-values

In [ ]:
# P-values for sklearn logistic regression.

# Class to display p-values for logistic regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values (LogisticRegression):
    
    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.X = X
        self.model.fit(X,y)
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
    
    def return_pvalues(self):
         #### Compute p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(self.X))))
        denom = np.tile(denom,(self.X.shape[1],1)).T
        F_ij = np.dot((self.X / denom).T,self.X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.coef_[0] / sigma_estimates # z-score for eaach model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values
        
        self.p_values = p_values
        return self.p_values

In [ ]:
logreg2 = LogisticRegression_with_p_values()

In [ ]:
logreg2.fit(inputs_train, loan_data_targets_train)

In [ ]:
#Sanity check to ensure the new model also computes the same coefficients

summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(logreg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', logreg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

In [ ]:
# Get p-values computed in a list


p_values = logreg2.return_pvalues()
p_values

In [ ]:
# Add the intercept = nan for completeness. 
p_values = np.append(np.nan, np.array(p_values))

In [ ]:
# Add p_values to the summary table
summary_table['p_values'] = p_values
summary_table

In [ ]:
# Find features having that are statistically significant

# if p-value < 0.05 then statistically significant
# if p-value > 0.05 then statistically not significant

summary_table[summary_table.p_values > 0.05]

Each independent variable is reprensented by several dummy variables

Rule - if a few the dummy variables are statistically significant then  it is best to retain all dummy variables that represent the original independent variable


## addr_state

addr_state:NM_VA is not signigicant but We will keep it because it has other statistically signficant dummy variables.


## verification_status

verification_status:Source Verified is not signigicant but We will keep it because it has other statistically signficant dummy variables.


## delinq_2yrs

We remove delinq_2yrs because both dummy variables (delinq_2yrs:0 & delinq_2yrs:1-3) are not statistically significant

## open_acc


All dummy variables are statistically not significant so we drop open_acc

## pub_rec

All dummy variables are statistically not significant so we drop pub_rec

## total_acc

All dummy variables are statistically not significant so we drop total_acc

## total_rev_hi_lim

All dummy variables are statistically not significant so we drop  total_rev_hi_lim

In [ ]:
# keep only statistically significant independent variables

inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [ ]:
# list containing reference categories for statistically significant variables

ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

In [ ]:
#sanity check

inputs_train.shape

In [ ]:
# Build a model using only the statistically significant independent variables

logreg3=LogisticRegression_with_p_values()
logreg3.fit(inputs_train, loan_data_targets_train)

In [ ]:
feature_name = inputs_train.columns.values

In [ ]:
#Same as before. Build a summary table 

summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(logreg3.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', logreg3.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

In [ ]:
# Compute and add p-value to the summary table just like before
p_values = logreg3.return_pvalues()
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table

In [ ]:
#save the final model

import pickle

pickle.dump(logreg3, open("pd_model.sav",'wb'))

## PD Model Validation (Test)

Testing using out of training samples (Test set)

In [ ]:
# Take the same variables that we used to train the PD model
inputs_test_with_ref_cat = loan_data_inputs_test.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [ ]:
# Keep the same reference categories that we used to train the model
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
inputs_test = inputs_test_with_ref_cat.drop(ref_categories, axis = 1)
inputs_test.head()

We are going to train the last model i.e logreg3 on the test set

In [ ]:
# Calculates the predicted values for the dependent variable (targets) based on inputs_test
y_hat_test = logreg3.model.predict(inputs_test)

In [ ]:
#sanity check
y_hat_test.shape

Note the predict function only predicts the class (1- non default(good) and 0 - default(bad))

By default, logistic regression computes the probability of default and for samples having probability > 0.5 it predicts no default and for samples < 0.5 it predicts default.

Is 0.5 a good threshold?

Why not use 0.45 or 0.55 as a threshold if it yeilds a better performance on the test set.

We will take a closer look this problem

First let's compute the probability instead of class prediction.

In [ ]:
# Use predict_proba instead of predict to compute probability instead of prediction a class.

y_hat_test_proba = logreg3.model.predict_proba(inputs_test)

In [ ]:
#Check
print (y_hat_test_proba.shape)
y_hat_test_proba

Note - the shape of y_hat_test_proba.

it has 2 columns for each sample in the test set.

In the first column is the probability of y_hat = 0  and in the second column is the probability of y_hat = 1

In [ ]:
# Take only the probabilities for y_hat =  1.

y_hat_test_proba[:][:,1]

In [ ]:
# Save y_hat=1 probabilities in a seperate list

y_hat_test_proba = y_hat_test_proba[: ][: , 1]

In [ ]:
# Sanity check
print (y_hat_test_proba.shape)
y_hat_test_proba

In [ ]:
# Create seperate variable and reset its index
loan_data_targets_test_temp = loan_data_targets_test
loan_data_targets_test_temp.reset_index(drop = True, inplace = True)

In [ ]:
# sanity check
loan_data_targets_test_temp.shape

In [ ]:
# concatenate both dataframes
df_actual_predicted_probs = pd.concat([loan_data_targets_test_temp, pd.DataFrame(y_hat_test_proba)], axis = 1)

In [ ]:
#check
df_actual_predicted_probs.shape

In [ ]:
# name the columns
df_actual_predicted_probs.columns = ['loan_data_targets_test', 'y_hat_test_proba']

In [ ]:
df_actual_predicted_probs.head()

## Checking model using accuracy

Accuracy is a simple measure. It is the percentage of samples correctly classified.

Now that we have a probability, we can use threshold to compute the accuracy.

## Suppose threshold = 0.5

In [ ]:
tr=0.5
# if predicted prob > 0.5 then predict 1 else predict 0

df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)

In [ ]:
df_actual_predicted_probs.shape

In [ ]:
df_actual_predicted_probs.head()

In [ ]:
# Create confusion matrix (See class notes to understand confusion matrix)

pd.crosstab(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test'], rownames = ['Actual'], colnames = ['Predicted'])

There is a problem here. The model is not picking the actual defaults i.e samples where actual = 0 (default)

# DIY 5

Write a function that takes actual and predicted lists as inputs and produces a confusion matrix.

Use the function to build the confusion matrix for 0.6,0.7,0.8 and 0.9.

Tell me which threshold yeilds the best results.

In [ ]:
def conf_matrix(actual,predicted):
    return pd.crosstab(actual, predicted, rownames = ['Actual'], colnames = ['Predicted'])

In [ ]:
tr=0.6
# if predicted prob > 0.5 then predict 1 else predict 0
df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)
conf_matrix(df_actual_predicted_probs['loan_data_targets_test'],df_actual_predicted_probs['y_hat_test'])

In [ ]:
tr=0.7
# if predicted prob > 0.5 then predict 1 else predict 0
df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)
conf_matrix(df_actual_predicted_probs['loan_data_targets_test'],df_actual_predicted_probs['y_hat_test'])

In [ ]:
tr=0.8
# if predicted prob > 0.5 then predict 1 else predict 0
df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)
conf_matrix(df_actual_predicted_probs['loan_data_targets_test'],df_actual_predicted_probs['y_hat_test'])

In [ ]:
tr=0.9
# if predicted prob > 0.5 then predict 1 else predict 0
df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)
conf_matrix(df_actual_predicted_probs['loan_data_targets_test'],df_actual_predicted_probs['y_hat_test'])

Accuracy of the model with tr = 0.9 can be computed as follows:

sum of samples correctly predicted / Total samples

In [ ]:
print ("accuracy = ", (7374+47256)/df_actual_predicted_probs.shape[0])

The accuracy is around 58%.

Can we do better?

Perhaps we can so we should vary the threhold and keep repeating the process till be find a threshold that gives us the maximum possible accuracy.

This is exactly what the ROC curve does for us.

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score

In [ ]:
# Function returns 3 arrays: tpr, fpr and thresholds

roc_curve(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test_proba'])

In [ ]:
# save the returned values in the varaibles

fpr, tpr, thresholds = roc_curve(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test_proba'])

In [ ]:
#check
print (fpr.shape)
print (tpr.shape)
print (thresholds.shape)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
# We plot the false positive rate along the x-axis and the true positive rate along the y-axis 
# This is definiton of ROC curve
plt.plot(fpr, tpr)
# Plot the diagonal which represents guessing
plt.plot(fpr, fpr, linestyle = '--', color = 'r')
# Axis labels and plot title
plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve')

We prefer a roc curve that is as close as possible to the top left corner.

in other words we prefer roc curve that maximizes the area under roc curve (AUCROC).

If your 3-4 competing models then you would compare them using AUCROC.

In [ ]:
AUROC = roc_auc_score(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test_proba'])

AUROC


## What is the best threshold though?

he choice of a threshold depends on the importance of TPR and FPR classification problem. For example, if based on your PD model if someone is predicted to be defaulter then dont give loan, false positives are very bad (deserving borrowers wont get loan which is bad for business). Thus you would choose a threshold that yields a low FPR while keeping a reasonable TPR (so deserving borrowers get credit).

In [ ]:
optimal_rate = tpr - fpr 
optimal_idx = np.argmax(optimal_rate)
best_thresh = thresholds[optimal_idx]
print('Best Threshold=%f' % (best_thresh))

In [ ]:
#Check the confusion matrix with the best threshold

tr=0.885971
# if predicted prob > 0.88597 then predict 1 else predict 0
df_actual_predicted_probs['y_hat_test'] = np.where(df_actual_predicted_probs['y_hat_test_proba'] > tr, 1, 0)
conf_matrix(df_actual_predicted_probs['loan_data_targets_test'],df_actual_predicted_probs['y_hat_test'])

In [ ]:
print ("accuracy = ", (6652+53485)/df_actual_predicted_probs.shape[0])

Accuracy has improved to around 64% as compared to 58% with threshold  = 0.9

## Applying the PD model built

We will begin by applying it to an individual account

In [ ]:
# Pick the first sample from the test set

inputs_test.iloc[:3,:]

In [ ]:
# For the first sample, convert into a series

first_sample = pd.DataFrame(inputs_test.loc[362514,:])

In [ ]:
first_sample

In [ ]:
summary_table

In [ ]:
# sanity check
print (summary_table.shape)
print (first_sample.shape)

For each variable having a 1 note the corresponding coefficient from the summary table

grade:C 0.684801
home_ownership:MORTGAGE  0.106251
addr_state:CA 0.062152
purpose:major_purch__car__home_impr 0.266262
mths_since_issue_d:40-41 0.778242
int_rate:12.025-15.74 0.306132
mths_since_earliest_cr_line:165-247 0.037159
inq_last_6mths:0	 0.666287
annual_inc:60K-70K 0.218096
dti:7.7-10.5  0.319723
mths_since_last_delinq:Missing 0.110415
mths_since_last_record:Missing 0.320884

In [ ]:
(-1.374064 + 0.684801 + 0.106251 + 0.062152 + 0.266262 + 0.778242 + 0.306132 +0.037159 + 0.666287 +0.218096 +0.319723+ 0.110415 + 0.32088 )

## ln ((1-PD)/PD) = 2.502336

In [ ]:
# Removing log

np.exp(2.502336)

## (1-PD)/PD  = 12.21

## Solving this we will get  PD = 0.075

## 1- PD = 0.925

## Probability of not defaulting for this sample is 0.925

In [ ]:
# This is sample proability computed by the PD model
y_hat_test_proba[0]

# DIY 6

Compute the probability of default for the 3rd sample

i.e sample haveing index = 213591 in inputs_test dataframe

Confirm your computation with the corrsponding value in y_hat_test_proba

In [ ]:
# Put sample in an numpy array
third_sample = np.array(inputs_test.loc[213591,:])

In [ ]:
#sanity check
third_sample.shape

In [ ]:
# Put all coefficients in another numpy array
coef = np.squeeze(logreg3.coef_)

In [ ]:
# Sanity check
coef.shape

In [ ]:
#Element wise multiplication of 2 arrays + intercept 

np.sum(np.multiply(third_sample,coef)) + logreg3.intercept_

In [ ]:
# Exponent of e
np.exp(2.04409937)

In [ ]:
# Solve for PD
PD = (1/8.72) 
PD

In [ ]:
1-PD # Prob of not defaulting

In [ ]:
# Confirmation with probability computed by PD model
y_hat_test_proba[2]

# Creating a score card for credit risk

In [ ]:
# Table contains features, coeficients and p-values
summary_table

In [ ]:
# reference categories that were not included in the model
ref_categories

In [ ]:
#Convert ref_categories which is a list into a dataframe
df_ref_categories = pd.DataFrame(ref_categories, columns = ['Feature name'])
# Add a column and sets its value to 0
df_ref_categories['Coefficients'] = 0
# Add a column to store values and set it to np.nan
df_ref_categories['p_values'] = np.nan
df_ref_categories

In [ ]:
# Join summary_table and df_ref_categories so that all features are in 1 dataframe
df_scorecard = pd.concat([summary_table, df_ref_categories])
#reset indexes of new dataframe
df_scorecard.reset_index(inplace=True)
df_scorecard

In [ ]:
#Get original feature name into a seperate column
df_scorecard['original_feature_name'] = df_scorecard['Feature name'].str.split(':').str[0]
df_scorecard

## Credit score ranges

In India credit scores range from 300-900

In [ ]:
min_score = 300
max_score = 900

In [ ]:
# Group by all coeficients by original feature and compute the min
df_scorecard.groupby('original_feature_name')['Coefficients'].min()

In [ ]:
#Store sum of all min co-efficients in a variable
min_sum_coef = df_scorecard.groupby('original_feature_name')['Coefficients'].min().sum()
min_sum_coef

In [ ]:
# similarly,Group by all coeficients by original feature and compute the max
df_scorecard.groupby('original_feature_name')['Coefficients'].max()

In [ ]:
#Store sum of all max co-efficients in a variable
max_sum_coef = df_scorecard.groupby('original_feature_name')['Coefficients'].max().sum()
max_sum_coef

###  score of 300 corresponds to the value in min_sum_coef

### score of 900 corresponds to the value in max_sum_coef

### Multiply the value of the 'Coefficients' column by the ratio of the differences between
### maximum score and minimum score and maximum sum of coefficients and minimum sum of cefficients.

In [ ]:
# Take each coeffient and scale it to be in desired range. This is similar to min-max scaling
df_scorecard['Score - Calculation'] = df_scorecard['Coefficients'] * (max_score - min_score) / (max_sum_coef - min_sum_coef)
df_scorecard

### Note the value in the intercept should be as close as possible to min_score

In [ ]:
# Handling the intercept
#We divide the difference of the value of the 'Coefficients' column and the minimum sum of coefficients by
# the difference of the maximum sum of coefficients and the minimum sum of coefficients.
# Then, we multiply that by the difference between the maximum score and the minimum score.
# Then, we add minimum score. 

df_scorecard['Score - Calculation'][0] = ((df_scorecard['Coefficients'][0] - min_sum_coef) / (max_sum_coef - min_sum_coef)) * (max_score - min_score) + min_score

In [ ]:
df_scorecard

In [ ]:
# Compute the min of all scores. it should be 300

min_sum_score_prel = df_scorecard.groupby('original_feature_name')['Score - Calculation'].min().sum()
min_sum_score_prel

In [ ]:
# # Compute the max of all scores. it should be 900
max_sum_score_prel = df_scorecard.groupby('original_feature_name')['Score - Calculation'].max().sum()
max_sum_score_prel

# Calculate credit score for all samples in test set

In [ ]:
inputs_test_with_ref_cat.head()

In [ ]:
df_scorecard

### Note there is an intercept in the 'Feature name' column which is not present in inputs_test_with_ref_cat

In [ ]:
# Adding intercept  and saving into a new variable

inputs_test_with_ref_cat_w_intercept = inputs_test_with_ref_cat
inputs_test_with_ref_cat_w_intercept.insert(0, 'Intercept', 1)
inputs_test_with_ref_cat_w_intercept

In [ ]:
inputs_test_with_ref_cat_w_intercept.head()

In [ ]:
# Remove the reference categories

inputs_test_with_ref_cat_w_intercept = inputs_test_with_ref_cat_w_intercept[df_scorecard['Feature name'].values]

In [ ]:
inputs_test_with_ref_cat_w_intercept.head()

In [ ]:
scorecard_scores = df_scorecard['Score - Calculation']

In [ ]:
inputs_test_with_ref_cat_w_intercept.shape

In [ ]:
scorecard_scores.shape

In [ ]:
# Reshape to allow dot product

scorecard_scores = scorecard_scores.values.reshape(102, 1)

In [ ]:
scorecard_scores.shape

In [ ]:
#y_scores = pd.DataFrame(np.dot(inputs_test_with_ref_cat_w_intercept,scorecard_scores))
y_scores = inputs_test_with_ref_cat_w_intercept.dot(scorecard_scores).round()

In [ ]:
y_scores.head()

## From credit score to PD

To go to sum of coefficients from score

1. Divide the difference between the scores and the minimum score by he difference between the maximum score and the minimum score.

2. Multiply the value in step 1  by the difference between the maximum sum of coefficients and the minimum sum of coefficients.

3. Add the minimum sum of coefficients

In [ ]:
# Goto sum_coef from score

sum_coef_from_score = ((y_scores - min_score) / (max_score - min_score)) * (max_sum_coef - min_sum_coef) + min_sum_coef

In [ ]:
# Divide an exponent raised to sum of coefficients from score by 
# an exponent raised to sum of coefficients from score plus one.

y_hat_proba_from_score = np.exp(sum_coef_from_score) / (np.exp(sum_coef_from_score) + 1)

In [ ]:
y_hat_proba_from_score.head()

In [ ]:
y_hat_test_proba[0: 5]

## Determine cut-offs

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score

In [ ]:
roc_curve(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test_proba'])

In [ ]:
fpr, tpr, thresholds = roc_curve(df_actual_predicted_probs['loan_data_targets_test'], df_actual_predicted_probs['y_hat_test_proba'])

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
plt.plot(fpr, tpr)
plt.plot(fpr, fpr, linestyle = '--', color = 'k')
plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve')

So far we have used the same code as before.

In [ ]:
print (thresholds.shape)
print (fpr.shape)
print (tpr.shape)

In [ ]:
# Concatenate the 3 dataframes
df_cutoffs = pd.concat([pd.DataFrame(thresholds), pd.DataFrame(fpr), pd.DataFrame(tpr)], axis = 1)

In [ ]:
# Give names to columns of df_cutoffs
df_cutoffs.columns  = ['thresholds','fpr','tpr']

In [ ]:
#check
df_cutoffs.head()

The first tow has a threshold which lead to fpr and tpr to be zero. We drop this row or we can set the value of the threshold to be 1

In [ ]:
## Set the first threshold (the value of the thresholds column to 1
df_cutoffs['thresholds'][0] = 1

The score corresponsing to each threshold equals:

The the difference between the natural logarithm of the ratio of the threshold and 1 minus the threshold and

the minimum sum of coefficients multiplied by

the sum of the minimum score and the ratio of the difference between the maximum score and minimum score and

the difference between the maximum sum of coefficients and the minimum sum of coefficients.

In [ ]:
# Compute score corresponding to each threshold
df_cutoffs['Score'] = ((np.log(df_cutoffs['thresholds'] / (1 - df_cutoffs['thresholds'])) - min_sum_coef) * ((max_score - min_score) / (max_sum_coef - min_sum_coef)) + min_score).round()

In [ ]:
df_cutoffs.head()

In [ ]:
# Set the score for first row to max
df_cutoffs['Score'][0] = max_score

In [ ]:
df_cutoffs.head()

In [ ]:
df_cutoffs.tail()

 Let us  define a function called 'n_approved' which assigns a value of 1 if a predicted probability
 
is greater than the parameter p, which is a threshold, and a value of 0, if it is not.

 Then it sums the column.
 
 Thus, if given any percentage values, the function will return 
 
the number of rows wih estimated probabilites greater than the threshold.

In [ ]:
#define the function described above
def n_approved(p):
    return np.where(df_actual_predicted_probs['y_hat_test_proba'] >= p, 1, 0).sum()

We will treat each sample in the test set as a new application for credit

For each threshold in df_cutoff we will compute the number of applications that will be approved

In [ ]:
# Compute number of applications that will be approved

df_cutoffs['N Approved'] = df_cutoffs['thresholds'].apply(n_approved)

In [ ]:
# Compute number of applications that will be rejected which is total - Number approved

df_cutoffs['N Rejected'] = df_actual_predicted_probs['y_hat_test_proba'].shape[0] - df_cutoffs['N Approved']

In [ ]:
# Compute approval and reject rates . 

df_cutoffs['Approval Rate'] = df_cutoffs['N Approved'] / df_actual_predicted_probs['y_hat_test_proba'].shape[0]

df_cutoffs['Rejection Rate'] = 1 - df_cutoffs['Approval Rate']

In [ ]:
df_cutoffs.head()

In [ ]:
df_cutoffs.tail()

In [ ]:
df_cutoffs.iloc[6000: 8000, ]

In [ ]:
# From previous work, we know the best threshold is 0.885971
# This threshold happens to be at index 6605
df_cutoffs.iloc[6605,: ]